<?php
// This is a SPIP language file  --  Ceci est un fichier langue de SPIP
// extrait automatiquement de http://trad.spip.net/tradlang_module/tipafriend?lang_cible=en
// ** ne pas modifier le fichier **

if (!defined('_ECRIRE_INC_VERSION')) return;

$GLOBALS[$GLOBALS['idx_lang']] = array(

	// B
	'bouton_activer' => 'Activate',
	'bouton_annuler' => 'Cancel',
	'bouton_desactiver' => 'Deactivate',
	'bouton_envoyer' => 'Send',
	'bouton_fermer' => 'Close',
	'bouton_reessayer' => 'Restart',
	'bouton_reset' => 'Reset',
	'bouton_send_by_mail' => 'Send via e-mail',
	'bouton_send_by_mail_ttl' => 'Send this page via e-mail',

	// C
	'cfg_legend_balise' => 'About the tag "#TIPAFRIEND"',
	'cfg_legend_patron' => 'About mail patrons',
	'cfg_legend_squelette' => 'About the submission form',
	'cfg_texte_descr' => 'This SPIP plugin adds a module to send a page (<i>its content, address and a message</i>) to one or more recipients via email.',
	'cfg_titre_descr' => 'Settings of the plugin <i>Tip A Friend</i>',
	'cfgform_comment_close_button' => 'Active by default; this option allows you to choose whether to show the \'close\' button at the bottom of the window; <strong>this option is automatically disabled if the headers above are disabled themselves </strong>.',
	'cfgform_comment_contenu' => 'Select the type of the SPIP content object (<i>article, news item, author, etc.</i>) to be included in the forwarded mail.',
	'cfgform_comment_header' => 'This option allows you to choose whether the <head> tag informations must be present or not on the page (<i>it may be useful to disable if you use a javascript window like \'thickbox\', or otherwise to force them to be displayed in a frame in the same context</i>).',
	'cfgform_comment_javascript' => 'You can disable the opening of the popup window (<i>in case of the use of javascript window type, for example, \'thickbox\' or \'fancybox\'</i>).',
	'cfgform_comment_options' => 'You must provide complete attributes, for example: "class=\'thickbox\'", they will automatically be added to the link in your skeletons ; <b>use only single quotes</b>.',
	'cfgform_comment_options_url' => 'Here you can specify a list of arguments, eg \'arg=value&arg2=new_value", they will be automatically added to the URL generated by the tag.',
	'cfgform_comment_patron' => 'default email patron in its classical version (<i>plain text</i>).',
	'cfgform_comment_patron_html' => 'If you use this option, the email sent will contain the first skeleton plain text version, leave the field blank to cancel this option.',
	'cfgform_comment_reset' => 'Here you can set the action of the "Cancel" button of the form (<i>redefine its action can allow you to close the thickbox window rather than a popup window eg</i>).',
	'cfgform_comment_squelette' => 'If you have created a personal skeleton for the dialog plugin window (<i>like the model file "tip_a_friend.html"</i>) enter it here ; your skeleton will necessarily include the form "<b>tipafriend_form</b>".',
	'cfgform_comment_taf_css' => 'the plugin defines CSS styles on the model of the SPIP\'s distribution ; by default, these styles are included in the form but you can here choose not to include them.',
	'cfgform_info_balise' => 'The tag returns the link to open the form page. You can change the image displayed by directly editing the skeleton "<strong>modeles/tipafriend.html</strong>" in the plugin.', # MODIF
	'cfgform_info_patron_html' => 'If the plugin <a href="http://www.spip-contrib.net/?article3371"><strong>Facteur</strong></a> is installed and running on your site it is possible to construct an HTML version of the email sent.',
	'cfgform_info_patrons' => 'Your personal patrons are to be placed in the subdirectory "<strong>patrons/</strong>" of your skeletons directory.',
	'cfgform_info_squelettes' => 'Your personal skeletons are to be placed directly in your home skeletons directory.',
	'cfgform_option_contenu_introduction' => 'The title and introduction',
	'cfgform_option_contenu_rien' => 'Nothing',
	'cfgform_option_contenu_tout' => 'The whole object',
	'cfgform_titre_close_button' => 'Include the \'Close\' button',
	'cfgform_titre_contenu' => 'Content of the SPIP objects included in the message',
	'cfgform_titre_header' => 'Include HTML headers',
	'cfgform_titre_javascript' => 'Standard javascript function (opening a popup)',
	'cfgform_titre_options' => 'Attribute(s) added to the link created by the tag',
	'cfgform_titre_options_url' => 'Argument(s) added to the URL of the link created by the tag',
	'cfgform_titre_patron' => 'Sent mail patron',
	'cfgform_titre_patron_html' => 'Sent mail HTML patron',
	'cfgform_titre_reset' => 'Cancel button action',
	'cfgform_titre_squelette' => 'Skeleton used for the tipafriend form',
	'cfgform_titre_taf_css' => 'Include defaut CSS definitions',

	// D
	'doc_chapo' => 'Le plugin "Tip A Friend" propose un formulaire complet pour envoyer une page d\'un site SPIP ({n\'importe laquelle}) à une liste d\'adresses e-mail.', # NEW
	'doc_en_ligne' => 'Documentation du plugin sur Spip-Contrib', # NEW
	'doc_titre_court' => 'Documentation TipAFriend', # NEW
	'doc_titre_page' => 'Documentation du plugin "Tip A Friend"', # NEW
	'docskel_sep' => '----', # NEW
	'documentation' => '
Cette page vous permet de tester l\'utilisation du plugin en fonction de votre site, de votre configuration et de vos personnalisations. Les différents liens proposés ajoutent un objet SPIP ou incluent un modèle dans le corps de la page. Vous pouvez modifier ces inclusions en éditant le paramètre correspondant de l\'URL courante.

{{{La balise TIPAFRIEND}}}

{{Utilisation}}

Le plugin propose une balise qui construit un lien ouvrant la page d\'envoi du mail d\'information en fonction de l\'objet SPIP courant. Cette balise accepte un unique argument, optionnel, permettant de définir :
-* soit {{le squelette utilisé pour générer ce lien}}, il faut alors indiquer le nom du squelette en question ({sans l\'extension ".html"}) ; le squelette doit être présent dans votre répertoire de modèles ;
-* soit {{le type de lien présenté}} ; si vous indiquez l\'argument "{{mini}}", la balise renverra uniquement l\'image du lien, sans le texte "Envoyer cette page ...".

{{Exemple}}

<cadre class="spip">
// balise seule
#TIPAFRIEND
// pour ne voir que l\'image
#TIPAFRIEND{mini}
// ou avec un modele personnel
#TIPAFRIEND{mon_modele}
</cadre>

{{Tests}}

Les liens ci-dessous ajoutent un objet SPIP à la page courante, laissant apparaître le rendu de la balise TIPAFRIEND.
- [Ajouter l\'article 1->@url_article@] <small>(id_article=...)</small>
- [Ajouter la brève 2->@url_breve@] <small>(id_breve=...)</small>
- [Recalculer la page->@url_recalcul@]
- [Retour à la page vierge->@url_vierge@]

Pour modifier l\'argument de la balise dans cette page de tests, ajoutez l\'argument "{{arg=...}}" à l\'URL courante ({par exemple pour utiliser l\'argument "mini", cliquez dans la barre d\'adresse de votre navigateur et ajoutez à la fin de l\'adresse courante "&arg=mini"}).

{{{Les modèles}}}

Les liens ci-dessous vous permettent de tester les modèles utilisés en page web ({avec des valeurs fictives}) ou de les inclure à la page courante.
- [Inclure le modèle \'tipafriend_mail_default.html\'->@url_model@] <small>(model=...)</small>
- [Voir le modèle brut avec des données fictives->@url_model_brut@]
- [Voir le modèle HTML avec des données fictives->@url_model_html@] <small>(nécessite le plugin {{[Facteur->http://www.spip-contrib.net/?article3371]}})</small>

{{{Paramètres de CFG pour TIPAFRIEND}}}

Si le plugin {{[CFG : moteur de configuration->http://www.spip-contrib.net/?rubrique575]}} est actif sur votre site, le lien ci-dessous vous présente les valeurs de configuration enregistrées pour le plugin "Tip A Friend".

@cfg_param@', # NEW

	// E
	'error_dest' => 'You have not specified recipient',
	'error_exp' => 'You have not entered your e-mail address',
	'error_exp_nom' => 'You must specify your name',
	'error_not_mail' => 'It seems that the address you entered is not an e-mail',
	'error_one_is_not_mail' => 'It seems that at least one of the addresses entered is not an e-mail',

	// F
	'form_dest_label' => 'Recepients e-mail addresses',
	'form_exp_label' => 'Your e-mail address',
	'form_exp_nom_label' => 'Your name',
	'form_exp_send_label' => '<em>Send you a copy of the mail ("Cc" field)</em>',
	'form_intro' => 'To transmit the address of this page, enter the e-mail addresses of your contacts and your own e-mail address and name. You can add a comment that will be included in the message body.<br /> <small>{{*}} {None of these informations will be kept.}</small>',
	'form_message_label' => 'You can add a text',
	'form_separe_virgule' => '<em>You can enter multiple addresses separated by a semicolon.</em>',
	'form_title' => 'Send a page by e-mail',

	// I
	'info_doc' => 'Si vous rencontrez des problèmes pour afficher cette page, [cliquez-ici->@link@].', # NEW
	'info_doc_titre' => 'Note concernant l\'affichage de cette page', # NEW
	'info_skel_doc' => 'Cette page de documentation est conçue sous forme de squelette SPIP fonctionnant avec la distribution standard ({fichiers du répertoire "squelettes-dist/"}). Si vous ne parvenez pas à visualiser la page, ou que votre site utilise ses propres squelettes, les liens ci-dessous vous permettent de gérer son affichage :

-* [Mode "texte simple"->@mode_brut@] ({html simple + balise INSERT_HEAD})
-* [Mode "squelette Zpip"->@mode_zpip@] ({squelette Z compatible})
-* [Mode "squelette SPIP"->@mode_spip@] ({compatible distribution})', # NEW

	// L
	'licence' => 'Copyright © 2009 [Piero Wbmstr->http://www.spip-contrib.net/PieroWbmstr] distributed under [GNU GPL v3->http://www.opensource.org/licenses/gpl-3.0.html] license.',

	// M
	'mail_body_01' => '@nom_exped@ (contact : @mail_exped@) invites you to consult the document below, taken from the website @nom_site@, you may be interested in.',
	'mail_body_01_html' => '<strong>@nom_exped@</strong> (contact : <a href="mailto:@mail_exped@">@mail_exped@</a>) invites you to consult the document below, taken from the website <strong>@nom_site@</strong>, you may be interested in.',
	'mail_body_02' => '@nom_exped@ joins you this message :',
	'mail_body_02_html' => '@nom_exped@ joins your this message :',
	'mail_body_03' => 'Title of the document : \'@titre_document@\'',
	'mail_body_03_html' => 'Title of the document : \'@titre_document@\'',
	'mail_body_04' => 'Address of this page on the Internet : @url_document@',
	'mail_body_04_html' => 'Address of this page on the Internet : <a href="@url_document@">@url_document@</a>',
	'mail_body_05' => 'Content of the relevant page (in text version) : ',
	'mail_body_05_html' => 'Content of the relevant page : ',
	'mail_body_extrait' => '( extract ) ',
	'mail_titre_default' => 'Informations from website @nom_site@',
	'message_envoye' => 'OK - Your message has been sent.',
	'message_pas_envoye' => '!! - Your message could not be sent for some unknown reason ... We apologize, you can <a href="@self@" title="Reload the page">try again</a>.',

	// N
	'new_window' => 'New window',

	// P
	'page_test' => 'Test page (local)',
	'page_test_balise' => 'Rendu de la balise TIPAFRIEND', # NEW
	'page_test_cfg_pas_installe' => 'Le Plugin [CFG->http://www.spip-contrib.net/?rubrique575] ne semble pas installé ...', # NEW
	'page_test_fin_simulation' => '-- Fin de l\'inclusion pour simulation', # NEW
	'page_test_in_new_window' => 'Page de test en nouvelle fenêtre', # NEW
	'page_test_menu_inclure' => 'Inclure le modèle \'tipafriend_mail_default.html\'', # NEW
	'page_test_models_comment' => 'Les liens ci-dessous vous permettent de tester les modèles utilisés en page web (<i>avec des valeurs fictives</i>).', # NEW
	'page_test_test_model_brut' => 'Voir le modèle brut avec des données fictives', # NEW
	'page_test_test_model_html' => 'Voir le modèle HTML avec des données fictives', # NEW
	'page_test_title' => 'Test du plugin "Tip A Friend"', # NEW
	'page_test_titre_inclusion_model' => '-- Inclusion du modèle \'@model@\' (<i>valeurs fictives</i>)', # NEW
	'page_test_titre_inclusion_objet' => '-- Simulation de page de @objet@ n° @id_objet@ (<i>titre + introduction</i>)', # NEW
	'popup_name' => 'Send an information by e-mail',

	// T
	'taftest_arguments_balise_dyn' => 'Arguments reçus dans balise dynamique', # NEW
	'taftest_arguments_balise_stat' => 'Arguments reçus dans balise statique', # NEW
	'taftest_chargement_patron' => 'chargement du patron \'@patron@\'', # NEW
	'taftest_content' => '<b><u>Détails du mail envoyé</u></b>', # NEW
	'taftest_contexte_modele' => 'Contexte envoyé au modèle', # NEW
	'taftest_creation_objet_champs' => 'Création d\'un objet \'Champs\' pour l\'ID objet', # NEW
	'taftest_creation_objet_texte' => 'Création d\'un objet \'Texte\' pour le nom d\'objet', # NEW
	'taftest_from' => '<b><i>Expéditeur</i></b>', # NEW
	'taftest_mail_content' => '<b><i>Corps du mail</i></b>', # NEW
	'taftest_mail_content_html' => '<b><i>Corps du mail version HTML</i></b>', # NEW
	'taftest_mail_headers' => '<b><i>Headers</i></b>', # NEW
	'taftest_mail_retour' => '<b><i>Retour de la fonction mail()</i></b>', # NEW
	'taftest_mail_title' => '<b><i>Titre du mail</i></b>', # NEW
	'taftest_modele_demande' => 'Modèle demandé par l\'utilisateur', # NEW
	'taftest_param_form' => 'Paramètres transmis au formulaire', # NEW
	'taftest_patron_pas_trouve' => 'Le patron \'@patron@\' n\'a pas été trouvé !<br />Chargement du patron par défaut.', # NEW
	'taftest_skel_pas_trouve' => 'Le squelette \'@skel@\' n\'a pas été trouvé !<br />Chargement du squelette par défaut.', # NEW
	'taftest_title' => 'TipAFriend DEBUG', # NEW
	'taftest_to' => '<b><i>Destinataires</i></b>', # NEW
	'tipafriend' => 'Tip A Friend'
);

?>
