-
  saisie: radio
  options:
    nom: variante
    label: <:foundation:version:>
    explication: <:foundation:version_explication:>
    datas:
      0: <:foundation:desactiver:>
      3: <:foundation:foundation_3:>
      4: <:foundation:foundation_4:>
      5: <:foundation:foundation_5:>
-
  saisie: oui_non
  options:
    nom: javascript
    label: <:foundation:activer_javascript:>
    explication: <:foundation:activer_javascript_explication:>
-
  saisie: oui_non
  options:
    nom: fichier_htc
    label: <:foundation:fichier_htc:>
    explication: <:foundation:fichier_htc_explication:>
-
  saisie: oui_non
  options:
    nom: foundation-icons
    label: <:foundation:icons:>
    explication: <:foundation:icons_explication:>