<?php

# This is a SPIP lang file
# autogenerated by "gettext" plugin
# for module "gettext" and lang "fr"


$GLOBALS[$GLOBALS['idx_lang_meta']] = array(
	'MIME-Version' => "1.0",
	'Content-Type' => "text/plain; charset=UTF-8",
	'Content-Transfer-Encoding' => "8bit",
	'Project-Id-Version' => "GetText pour SPIP",
	'POT-Creation-Date' => "",
	'PO-Revision-Date' => "",
	'Last-Translator' => "Matthieu Marcillaud <marcimat@rezo.fr>",
	'Language-Team' => "<spip-trad@rezo.net>",
	'X-Poedit-Language' => "French",
);

$GLOBALS[$GLOBALS['idx_lang']] = array(

	// C
	'choisir_fichiers' => "Fichiers à transposer",
	'choisir_fichiers_explication' => "Choisir les fichiers à transposer",

	// D
	'dans_repertoire' => "Dans le répertoire <code>@dir@</code>",

	// E
	'erreur_chemin_a_definir' => "Merci d'indiquer un chemin ! (et un seul !)",
	'erreur_chemin_pas_accessible_ecriture' => "Le chemin indiqué n'est pas accessible en écriture",
	'erreur_chemin_pas_accessible_lecture' => "Le chemin indiqué n'est pas accessible en lecture",
	'erreur_chemin_pas_repertoire' => "Le chemin indiqué n'est pas un répertoire valide",
	'erreur_chemin_un_seul' => "Merci de ne choisir qu'un seul chemin :) ... faites un choix !",
	'erreur_fichier_non_accessible_ecriture' => "Le fichier '@file@' n'est pas accessible en écriture.",
	'erreur_presente' => "Une erreur est présente dans la saisie",
	'erreur_reperoire_pas_accessible_ecriture' => "Le répertoire '@dir@' doit être accessible en écriture.",
	'etape' => "Étape @nb@/@nbs@",
	'exporter_en_po' => "Exporter en .po",

	// I
	'import_export_po' => "Import/Export de .po",
	'importer_en_spip' => "Importer en spip",

	// O
	'operation_reussie' => "L'opération a été effectuée avec succès.",

	// P
	'precedent' => "Précédent",

	// S
	'selection_action' => "Sélectionner l'action à réaliser",
	'selection_repertoire' => "Chemin du répertoire lang/",
	'selection_repertoire_explication' => "Indiquer un chemin de répertoire de langue,
		pour permettre de trouver la liste des fichiers de langues et les transformer en fichiers .po
		ou inversement. Ce répertoire doit être accessible en écriture pour que les fichiers puissent
		être créés. Exemple <code>/home/marcimat/www/spip/plugins/souk/gettext/lang</code> .",
	'selection_repertoire_propose' => "Ou choisir un chemin proposé",
	'selection_repertoire_propose_explication' => "Vous pouvez alternativement choisir un chemin
		parmis ceux trouvés :",
	'suivant' => "Suivant",

	// T
	'to_po' => "Passer de SPIP à .PO",
	'to_spip' => "Passer de .PO à SPIP",
);
?>
