<?php
// This is a SPIP language file  --  Ceci est un fichier langue de SPIP
// extrait automatiquement de http://trad.spip.org/tradlang_module/saveauto?lang_cible=en
// ** ne pas modifier le fichier **

if (!defined('_ECRIRE_INC_VERSION')) return;

$GLOBALS[$GLOBALS['idx_lang']] = array(

	// A
	'attention' => 'Warning:',

	// C
	'colonne_date' => 'Date',
	'colonne_nom' => 'Name',
	'colonne_taille_octets' => 'Size',

	// E
	'envoi_mail' => 'Backups sent',
	'erreur_config_inadaptee_mail' => 'Inappropriate configuration - your server does not offer email dispatch functionality!',
	'erreur_impossible_creer_verifier' => 'Can not create the @fichier@ file: check write access rights are available for the @rep_bases@ directory.',
	'erreur_impossible_liste_tables' => 'Can not list the tables in the database.',
	'erreur_mail_fichier_lourd' => 'The backup file is too large to be sent by email. You may retrieve a copy using your site administration interface or  via FTP using the file path: @fichier@',
	'erreur_mail_sujet' => 'SQL backup error',
	'erreur_probleme_donnees_corruption' => 'Problem with data in the @table@ table, it may be corrupted!',
	'erreur_repertoire_inaccessible' => 'The @rep@ directory is not open for write access.',
	'erreur_repertoire_inexistant' => 'The @rep@ directory does not exist. Please check your site structure configuration.',
	'erreur_sauvegarde_intro' => 'The error message is as follows:',
	'erreurs_config' => 'Configuration error(s) exist',

	// H
	'help_accepter' => 'Optional: only save the tables with a particular string included in the table name, e.g. directory_, important, thing.
             Enter nothing to accept all tables in the database. Separate different specific names with a semi-colon (;)',
	'help_envoi' => 'Optional: sends the backup by email if you enter a recipient email address',
	'help_eviter' => 'Optional: if the table contains the specified string in its name: the data are ignored (but not the structure). Separate the different names with a semi-colon (;).',
	'help_gz' => 'Otherwise the backups will be in .sql format.',
	'help_mail_max_size' => 'Certain databases may exceed the maximum size for documents attached to an email. Check with your web host to find out the maximum size authorised. The default limit is 2 MB.',
	'help_msg' => 'Display a successful completion message on the screen',
	'help_obsolete' => 'Based on the number of days old, determine if an archive is considered as obsolete and if so delete it from the server.
             Enter -1 to deactivate this functionality',
	'help_prefixe' => 'Optional: enter a prefix for the backup file name',
	'help_rep' => 'Directory for storing the files (the path starting from the SPIP <strong>root</strong> directory, tmp/data/ for example). It <strong>MUST</strong> end with a /.',
	'help_restauration' => '<strong>Warning !!!</strong> the backups made are <strong>not in SPIP format</strong> :
                It is useless to try to use them with the SPIP administration tool.<br /><br />
             For any backup restores, you must use the <strong>phpmyadmin</strong> interface of your
             database server: on the <strong>"SQL"</strong> tab, use the button labelled
             <strong>"Location of the text file"</strong> to select the backup file
             (tick the "gzipped" option if necessary) then click on OK.<br /><br />
             The <strong>xxxx.gz</strong> or <strong>xxx.sql</strong> backups contain an SQL formatted file with the commands 
             used to <strong>delete</strong> the existing SPIP tables and to <strong>replace</strong> them with
             archived data. Any data <strong>more recent</strong> than those in the backup will therefore be <strong>LOST</strong>!',
	'help_titre' => 'This page is used to configure the automatic database backup options.',

	// I
	'info_mail_message_mime' => 'This is a MIME-formatted message.',
	'info_sauvegardes_obsolete' => 'A backup of the database is stored @nb@ days from the date of its production.',
	'info_sql_base' => 'Database:',
	'info_sql_compatible_phpmyadmin' => 'SQL file 100% compatible with PHPMyadmin',
	'info_sql_date' => 'Date:',
	'info_sql_debut_fichier' => 'Start of file',
	'info_sql_donnees_table' => 'Data from @table@',
	'info_sql_fichier_genere' => 'This file is generated by the saveauto plugin',
	'info_sql_fin_fichier' => 'End of file',
	'info_sql_ipclient' => 'Client IP:',
	'info_sql_mysqlversion' => 'MySQL version:',
	'info_sql_os' => 'Server O/S:',
	'info_sql_phpversion' => 'PHP version:',
	'info_sql_plugins_utilises' => '@nb@ plugins used:',
	'info_sql_serveur' => 'Server:',
	'info_sql_spip_version' => 'SPIP version:',
	'info_sql_structure_table' => 'Structure of the @table@ table',
	'info_telecharger_sauvegardes' => 'The table below lists all downloadable backups made for your site.',

	// L
	'label_adresse' => 'To the address:',
	'label_compression_gz' => 'Zip the backup file:',
	'label_donnees' => 'Data from the tables:',
	'label_donnees_ignorees' => 'Data ignored:',
	'label_frequence' => 'Frequency of the backup: every',
	'label_mail_max_size' => 'Maximum size of files attached to emails (MB):',
	'label_message_succes' => 'Display a successful completion message if the backup runs OK:',
	'label_nom_base' => 'SPIP database name:',
	'label_obsolete_jours' => 'Backups considered as obsolete after:',
	'label_prefixe_sauvegardes' => 'Backup prefix:',
	'label_repertoire_stockage' => 'Storage directory:',
	'label_restauration' => 'Restore a backup:',
	'label_structure' => 'Structure of the tables:',
	'label_tables_acceptes' => 'Tables accepted:',
	'legend_structure_donnees' => 'Items to be backed up:',

	// M
	'message_aucune_sauvegarde' => 'There are no backups.',
	'message_pas_envoi' => 'The backups will not be emailed!',

	// S
	'sauvegarde_erreur_mail' => 'The "saveauto" plugin encountered an error during the database backup.',
	'sauvegarde_ok_mail' => 'Database backup and dispatch via email completed successfully!',
	'saveauto_titre' => 'SQL backup',

	// T
	'titre_boite_historique' => 'Backup history',
	'titre_boite_sauver' => 'Saveauto plugin: SQL database backups',
	'titre_page_saveauto' => 'Database backups',
	'titre_saveauto' => 'Automatic backups',

	// V
	'valeur_jours' => ' days'
);

?>
