<?php
// This is a SPIP language file  --  Ceci est un fichier langue de SPIP
// extrait automatiquement de http://trad.spip.net/tradlang_module/smush?lang_cible=en
// ** ne pas modifier le fichier **

if (!defined('_ECRIRE_INC_VERSION')) return;

$GLOBALS[$GLOBALS['idx_lang']] = array(

	// E
	'erreur_copie_locale' => 'The file could not be copied locally (@src@).',
	'erreur_pas_image' => 'The file does not seem to be an image png, jpg or gif (@src@).',

	// I
	'info_gain' => 'The gain is @gain@ bytes or @gain_octets@ (@percent@%).',
	'info_gain_simple' => 'The gain is @gain@ bytes (@percent@%).',
	'info_impossible_utilisation_locale' => 'The necessary softwares for local use are not all present.',
	'info_logiciel_nok' => 'The software"@logiciel@" is not available',
	'info_logiciel_nok_tous' => 'All the necessary software are not usable. You can not use smush locally.',
	'info_logiciel_ok' => 'The software "@logiciel@" seems usable',
	'info_logiciel_ok_tous' => 'All the necessary software are usable. You can use smush locally.',
	'info_taille' => 'Size : @taille@ (@octets@).',
	'info_titre_smush' => 'Smush',

	// L
	'label_eviter_traitement_auto' => 'Avoid the automatic processing of all the images generated by SPIP',
	'label_url_test' => 'Url of your image to test',

	// S
	'smush_conf_descriptif' => 'The plugin Smush can reduce the image size to the minimum using specific softwares on the server. This page allows you to configure it.',

	// T
	'titre_test_logiciels' => ' Software test presence',
	'titre_testeur_smush' => 'Test on a picture',
	'titre_version_originale' => 'Originale version',
	'titre_version_smushed' => 'Optimised version'
);

?>
