CREATE TABLE `spip_boutique_produits` (
  `id_produit` bigint(20) NOT NULL auto_increment,
  `token` text NOT NULL,
  `titre` text NOT NULL,
  `soustitre` text NOT NULL,
  `descriptif` text NOT NULL,
  `texte` longblob NOT NULL,
  `logo` text NOT NULL,
  `url_site` varchar(255) NOT NULL,
  `nom_site` tinytext NOT NULL,
  `id_categorie` bigint(20) NOT NULL,
  `id_mot` bigint(20) NOT NULL,
  `id_parent` bigint(20) NOT NULL,
  `id_secteur` bigint(20) NOT NULL,
  `id_gamme` bigint(20) NOT NULL,
  `prix_achat` bigint(20) NOT NULL,
  `prix_vente` bigint(20) NOT NULL,
  `tva` bigint(20) NOT NULL,
  `lang` varchar(10) NOT NULL,
  `lang_choisie` varchar(3) NOT NULL,
  `statut` varchar(10) NOT NULL,
  `date` datetime NOT NULL,
  `date_redac` datetime NOT NULL,
  `date_modif` datetime NOT NULL,
  PRIMARY KEY  (`id_produit`)
) TYPE=MyISAM ;
