#!/bin/bash
VERSION=1
SANS_ARGS=0 
E_ERREUROPTION=65

#Récupération des differents chemins
#Si on est dans le répertoire plugins ou dans un de ses sous répertoires ex : plugins/saisies
if [[ "`pwd| grep plugins`" ]]; then
    repertoire_racine=${PWD%/plugins*}
    repertoire_plugins=$repertoire_racine/plugins
    repertoire_executables=$repertoire_plugins/spipenconsole
# Si on est à la racine du spip
elif [[ -d plugins-dist ]]; then
    repertoire_racine=${PWD}
    repertoire_plugins=$repertoire_racine/plugins
    repertoire_executables=$repertoire_plugins/spipenconsole
else    
    echo ""
    echo "Vous devez vous placer soit :"
    echo " - A la racine du spip,"
    echo " - Dans le répertoire plugins ou l'un de ses sous répertoires ! (ex : plugins/saisies)"
    echo ""
    exit
fi

if [ $# -eq "$SANS_ARGS" ]  # Script appelé sans argument?
then
    $repertoire_executables/lister_plugins.php "$repertoire_executables"
fi  

function F_aide(){
echo "`basename $0`, version 1"
echo ""
echo "syntaxe: spipenconsole -[arguments][options]"
echo "exemple : spipenconsole -a saisies,z  -> activera les plugins saisies et Z"
echo ""
echo "ATTENTION : spipenconsole fonctionne seulement si vous etes :"
echo " - A la racine du spip,"
echo " - Dans le répertoire plugins ou l'un de ses sous répertoires ! (ex : plugins/saisies)"
echo ""
echo "-h : help"
echo "-v : version"
echo "-l : liste tous les plugins, s'il y a un astérisque \"*\", le plugin est activé "
echo "-a : activer un ou des plugins séparés par une \",\" : saisie,yaml"
echo "-d : désactiver un ou des plugins séparés par une \",\" : saisie,yaml, l'argument --all désactive tous les plugins."
echo "-t : svn checkout du plugin, on donne le nom du plugin (celui de la zone) et son repertoire : trunk, branches, ou rien"
echo "-f : svn checkout des plugins contenus dans le fichier telecharger.csv : colonne1=nom_plugin,colonne2=repertoire"
echo "-c : vider le cache : local et tmp/cache"
echo ""
echo "Il est possible de faire un lien symbolique de cet exécutable soit :"
echo "  - vers le répertoire plugins."
echo "  - vers le répertoire racine." 
echo "avec la commande  'ln -s plugins/spipenconsole/spipenconsole .'(si vous etes dans le répertoire racine)"
echo ""
echo "Il est possible aussi de créer un alias dans son .bashrc ou .zshrc ..."
}

function F_vider_cache(){
    rm -rf $repertoire_racine/tmp/cache/*
    rm -rf $repertoire_racine/local/*
    echo "les repertoires tmp et local sont vides"
}

while getopts vhlca:d:t:f option
do
    case $option in
        v)   
            echo "`basename $0` $VERSION"
            ;;
        h)
            F_aide
            ;;
        l)
            $repertoire_executables/lister_plugins.php "$repertoire_executables"
            ;;
        a)
            liste_plugins_activer=${OPTARG//,/" "}
            $repertoire_executables/activer_plugin.php $liste_plugins_activer "$repertoire_racine/ecrire"
            $repertoire_executables/lister_plugins.php "$repertoire_executables"
            ;;
        d)
            liste_plugins_desactiver=${OPTARG//,/" "}
            $repertoire_executables/desactiver_plugin.php $liste_plugins_desactiver "$repertoire_racine/ecrire"
            $repertoire_executables/lister_plugins.php "$repertoire_executables"
            ;;
        c)
            F_vider_cache
            ;;
        t)
            OLDIFS="$IFS"
            IFS=,
            set $OPTARG
            IFS="$OLDIFS"; unset $OLDIFS
            svn checkout svn://zone.spip.org/spip-zone/_plugins_/${1}/${2} $repertoire_plugins/${1}
            ;;
        f)
            while IFS=, read nom dossier
            do  
                svn checkout svn://zone.spip.org/spip-zone/_plugins_/${nom}/${dossier} $repertoire_plugins/${nom}
            done < $repertoire_executables/telecharger.csv
            $repertoire_executables/lister_plugins.php "$repertoire_executables"
            ;;
    esac
done
