#!/bin/bash
VERSION=1
SANS_ARGS=0 
E_ERREUROPTION=65

#Récupération des differents chemins
if [[ "${PWD##*/}" = "plugins" ]]; then
    repertoire_executables=${PWD}/spipenconsole
    repertoire_plugin=${PWD}
    repertoire_racine=${PWD%/plugins}
elif [[ "${PWD##*/}" = "spipenconsole" ]]; then
    repertoire_executables=${PWD}
    repertoire_plugin=${PWD%/*}
    repertoire_racine=${PWD%/plugins/spipenconsole}
else
    repertoire_executables=${PWD}/plugins/spipenconsole
    repertoire_plugin=${PWD}/plugins
    repertoire_racine=${PWD}
fi

if [ $# -eq "$SANS_ARGS" ]  # Script appelé sans argument?
then
    $repertoire_executables/lister_plugins.php "$repertoire_executables"
fi  

function F_aide(){
echo "`basename $0`, version 1"
echo ""
echo "syntaxe: ..."
echo "-h : help"
echo "-v : version"
echo "-l : liste tous les plugins, s'il y a un astérisque \"*\", le plugin est activé "
echo "-a : activer un ou des plugins séparés par une \",\" : saisie,yaml"
echo "-d : désactiver un ou des plugins séparés par une \",\" : saisie,yaml, l'argument --all désactive tous les plugins."
echo "-t : svn checkout du plugin, on donne le nom du plugin (celui de la zone) et son repertoire : trunk, branches, ou rien"
echo "-f : svn checkout des plugins contenus dans le fichier telecharger.csv : colonne1=nom_plugin,colonne2=repertoire"
echo ""
echo "Il est possible de faire un lien symbolique de cet exécutable soit :"
echo "  - vers le répertoire plugins."
echo "  - vers le répertoire racine." 
echo "avec la commande  'ln -s plugins/spipenconsole/spipenconsole .'(si vous etes dans le répertoire racine)"

}


while getopts vhla:d:t:f option
do
    case $option in
        v)   
            echo "`basename $0` $VERSION"
            ;;
        h)
            F_aide
            ;;
        l)
            $repertoire_executables/lister_plugins.php "$repertoire_executables"
            ;;
        a)
            liste_plugins_activer=${OPTARG//,/" "}
            $repertoire_executables/activer_plugin.php $liste_plugins_activer "$repertoire_racine/ecrire"
            $repertoire_executables/lister_plugins.php "$repertoire_executables"
            ;;
        d)
            liste_plugins_desactiver=${OPTARG//,/" "}
            $repertoire_executables/desactiver_plugin.php $liste_plugins_desactiver "$repertoire_racine/ecrire"
            $repertoire_executables/lister_plugins.php "$repertoire_executables"
            ;;
        t)
            OLDIFS="$IFS"
            IFS=,
            set $OPTARG
            IFS="$OLDIFS"; unset $OLDIFS
            svn checkout svn://zone.spip.org/spip-zone/_plugins_/${1}/${2} $repertoire_plugin/${1}
            ;;
        f)
            while IFS=, read nom dossier
            do  
                svn checkout svn://zone.spip.org/spip-zone/_plugins_/${nom}/${dossier} $repertoire_plugin/${nom}
            done < $repertoire_executables/telecharger.csv
            #cd $repertoire_plugin/spipenconsole
            $repertoire_executables/lister_plugins.php "$repertoire_executables"
            ;;
    esac
done

