<?php
#              ACS
#          (Plugin Spip)
#     http://acs.geomaticien.org
#
# Copyright Daniel FAIVRE, 2007-2010
# Copyleft: licence GPL - Cf. LICENCES.txt
#
/**
 * ACS model default values
 *
 * On initialise les valeurs des variables du modèle
 */

$def=array(
'acsVersion'=>'0.7.1',
'acsModel'=>'cat',
'acsAgendaUse'=>'oui',
'acsAgendaTitreFondColor'=>'=acsRubnavTitreFond',
'acsAgendaTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsAgendaHeadFondColor'=>'=acsRubnavFond',
'acsAgendaBord'=>'=acsRubnavBord',
'acsAgendaNotThisMonth'=>'=acsRubnavFondHover',
'acsAgendaThisMonth'=>'=acsRubnavFond',
'acsAgendaThisDay'=>'=acsFondColor',
'acsAgendaBulleFondColor'=>'=acsRubnavFond6',
'acsAgendaBulleVoirArticlesModifies'=>'oui',
'acsAgendaBulleArticleModifieFondColor'=>'=acsRubnavFond4',
'acsAgendaBulleBreveFondColor'=>'=acsRubnavFond2',
'acsAgendaBulleSurvol'=>'=acsRubnavFondHover',
'acsArticlesUse'=>'oui',
'acsArticlesTabFirst'=>'#dfe5ef',
'acsArticlesTabOdd'=>'#e4dfef',
'acsArticlesTabEven'=>'#dfdfef',
'acsAudioUse'=>'oui',
'acsAudioFond'=>'=acsRubnavFond',
'acsAudioTitreFond'=>'=acsRubnavTitreFond',
'acsAudioTitreImage'=>'=acsRubnavTitreFondImage',
'acsAudioSep'=>'=acsRubnavSep',
'acsAudioMp3on'=>'=acsRubnavFond6',
'acsAudioMp3hover'=>'=acsRubnavFondHover',
'acsAuteursUse'=>'oui',
'acsAuteursFond'=>'=acsRubnavFond',
'acsAuteursTitreFond'=>'=acsRubnavTitreFond',
'acsAuteursTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsBandeauUse'=>'oui',
'acsBandeauFond'=>'=acsRubnavFond',
'acsBandeauTextColor'=>'#352d4d',
'acsBandeauBord'=>'a:3:{s:5:"Width";s:3:"1px";s:5:"Style";s:6:"groove";s:5:"Color";s:7:"#ffccf5";}',
'acsBandeauBordBas'=>'#c3d5c8',
'acsBandeauFontSize'=>'1em',
'acsBandeauLegende'=>'En construction - Under construction',
'acsBandeauAlignement'=>'center',
'acsBandeauContenu'=>'<a href="http://acs.geomaticien.org">ACS</a>: pour configurer ce site, <a href="ecrire/?exec=acs&onglet=composants&composant=fond">cliquez ici</a>.',
'acsBandeauText2'=>'-> <a href="ecrire/?exec=acs&onglet=composants&composant=bandeau">Modifier ce bandeau</a> <-',
'acsBanniereUse'=>'oui',
'acsBanniereFond'=>'#fcfcfc',
'acsBanniereFondImage'=>'titrefond_00.png',
'acsBanniereFondImageRepeatX'=>'non',
'acsBanniereFondImageRepeatY'=>'oui',
'acsBanniereFondAlign'=>'left',
'acsBanniereFondVerticalAlign'=>'top',
'acsBanniereAlign'=>'center',
'acsBanniereValign'=>'middle',
'acsBanniereHauteur'=>'60px',
'acsBanniereLogo'=>'non',
'acsBanniereLogoAlign'=>'left',
'acsBanniereFontFamily'=>'sans-serif',
'acsBanniereFont'=>'Verdana, Arial',
'acsBrevesUse'=>'oui',
'acsBrevesFond'=>'=acsRubnavFond',
'acsBrevesTitreFond'=>'=acsRubnavTitreFond',
'acsBrevesTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsCustomUse'=>'oui',
'acsEditoUse'=>'oui',
'acsFondUse'=>'oui',
'acsFondFavicon'=>'favicon.ico',
'acsFondColor'=>'#f4f4f4',
'acsFondText'=>'#002200',
'acsFondLink'=>'#00008d',
'acsFondLinkHover'=>'#0000f4',
'acsForumsUse'=>'oui',
'acsForumsTitreFond'=>'=acsRubnavTitreFond',
'acsForumsTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsForumsFond'=>'=acsRubnavFond',
'acsForumsBord'=>'=acsRubnavBord',
'acsForumsNb'=>'10',
'acsKeysUse'=>'oui',
'acsKeysFond'=>'=acsRubnavFond',
'acsKeysTitreFond'=>'=acsRubnavTitreFond',
'acsKeysTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsMailUse'=>'oui',
'acsMailTitreFond'=>'=acsRubnavTitreFond',
'acsMailTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsMailFond'=>'=acsRubnavFond',
'acsModuleUse'=>'oui',
'acsModule1Use'=>'oui',
'acsModule1Orientation'=>'vertical',
'acsModule11'=>'banniere',
'acsModule12'=>'bandeau',
'acsModule1ShadowSize'=>'5',
'acsModule1ShadowBlur'=>'5',
'acsModule1Comment'=>'Entête de page',
'acsModule3Use'=>'oui',
'acsModule3Orientation'=>'vertical',
'acsModule32'=>'ours',
'acsModule3ShadowSize'=>'5',
'acsModule3ShadowBlur'=>'5',
'acsModule3Comment'=>'Pied de page',
'acsModule2000Use'=>'oui',
'acsModule2000Orientation'=>'vertical',
'acsModule20001'=>'module-1',
'acsModule20002'=>'module-2005',
'acsModule20008'=>'module-3',
'acsModule2000ShadowSize'=>'5',
'acsModule2000ShadowBlur'=>'5',
'acsModule2000Comment'=>'Page sommaire',
'acsModule2001Use'=>'oui',
'acsModule2001Orientation'=>'vertical',
'acsModule2001Left'=>'10px',
'acsModule2001Right'=>'10px',
'acsModule20011'=>'recherche',
'acsModule20012'=>'rubnav',
'acsModule20013'=>'forums',
'acsModule2001ShadowSize'=>'5',
'acsModule2001ShadowBlur'=>'5',
'acsModule2001Comment'=>'Colonne gauche de la page sommaire',
'acsModule2002Use'=>'oui',
'acsModule2002Orientation'=>'vertical',
'acsModule2002Bord'=>'=acsOngletsBordColor',
'acsModule20021'=>'onglets',
'acsModule20022'=>'module-2004',
'acsModule20022style'=>'margin-top: -1px',
'acsModule2002ShadowSize'=>'5',
'acsModule2002ShadowBlur'=>'5',
'acsModule2002Comment'=>'Colonne centrale de la page sommaire',
'acsModule2003Use'=>'oui',
'acsModule2003Orientation'=>'vertical',
'acsModule2003Left'=>'10px',
'acsModule2003Right'=>'10px',
'acsModule20031'=>'agenda',
'acsModule2003ShadowSize'=>'5',
'acsModule2003ShadowBlur'=>'5',
'acsModule2003Comment'=>'Colonne droite de la page sommaire',
'acsModule2004Use'=>'oui',
'acsModule2004Orientation'=>'vertical',
'acsModule2004Fond'=>'=acsOngletsFondColor',
'acsModule2004Bord'=>'a:3:{s:5:"Width";s:3:"1px";s:5:"Style";s:5:"solid";s:5:"Color";s:7:"#dfdfdf";}',
'acsModule20041'=>'articles',
'acsModule20042'=>'',
'acsModule2004ShadowSize'=>'5',
'acsModule2004ShadowBlur'=>'5',
'acsModule2004Comment'=>'Onglet de la page sommaire',
'acsModule2005Use'=>'oui',
'acsModule2005Orientation'=>'horizontal',
'acsModule2005Top'=>'10px',
'acsModule20051'=>'module-2001',
'acsModule20051style'=>'width: 20%;',
'acsModule20052'=>'module-2002',
'acsModule20052style'=>'width: 60%;',
'acsModule20053'=>'module-2003',
'acsModule20053style'=>'width: 20%;',
'acsModule2005ShadowSize'=>'5',
'acsModule2005ShadowBlur'=>'5',
'acsModule2005Comment'=>'Bloc central de la page sommaire',
'acsModule2010Use'=>'oui',
'acsModule2010Orientation'=>'vertical',
'acsModule20101'=>'module-1',
'acsModule20102'=>'module-2015',
'acsModule20108'=>'module-3',
'acsModule2010ShadowSize'=>'5',
'acsModule2010ShadowBlur'=>'5',
'acsModule2011Use'=>'oui',
'acsModule2011Orientation'=>'vertical',
'acsModule2011Left'=>'=acsModule2001Left',
'acsModule2011Right'=>'=acsModule2001Right',
'acsModule20111'=>'recherche',
'acsModule20112'=>'rubnav',
'acsModule20113'=>'auteurs',
'acsModule2011ShadowSize'=>'5',
'acsModule2011ShadowBlur'=>'5',
'acsModule2011Comment'=>'Colonne gauche de la page resume',
'acsModule2013Use'=>'oui',
'acsModule2013Orientation'=>'vertical',
'acsModule2013Left'=>'=acsModule2003Left',
'acsModule2013Right'=>'=acsModule2003Right',
'acsModule20131'=>'agenda',
'acsModule2013ShadowSize'=>'5',
'acsModule2013ShadowBlur'=>'5',
'acsModule2013Comment'=>'Colonne droite de la page resume',
'acsModule2015Use'=>'oui',
'acsModule2015Orientation'=>'horizontal',
'acsModule2015Top'=>'=acsModule2005Top',
'acsModule20151'=>'module-2011',
'acsModule20151style'=>'=acsModule20051style',
'acsModule20152'=>'module-2002',
'acsModule20152style'=>'=acsModule20052style',
'acsModule20153'=>'module-2013',
'acsModule20153style'=>'=acsModule20053style',
'acsModule2015ShadowSize'=>'5',
'acsModule2015ShadowBlur'=>'5',
'acsModule2015Comment'=>'Bloc central de la page resume (3 colonnes)',
'acsModule2020Use'=>'oui',
'acsModule2020Orientation'=>'vertical',
'acsModule20201'=>'module-1',
'acsModule20201style'=>'',
'acsModule20202'=>'module-2025',
'acsModule20202style'=>'',
'acsModule20208'=>'module-3',
'acsModule2020ShadowSize'=>'5',
'acsModule2020ShadowBlur'=>'5',
'acsModule2020Comment'=>'Page plan',
'acsModule2021Use'=>'oui',
'acsModule2021Orientation'=>'vertical',
'acsModule2021Left'=>'=acsModule2001Left',
'acsModule2021Right'=>'=acsModule2001Right',
'acsModule20211'=>'rubnav',
'acsModule2021ShadowSize'=>'5',
'acsModule2021ShadowBlur'=>'5',
'acsModule2021Comment'=>'Colonne gauche de la page plan',
'acsModule2025Use'=>'oui',
'acsModule2025Orientation'=>'horizontal',
'acsModule2025Right'=>'10px',
'acsModule2025Top'=>'=acsModule2005Top',
'acsModule20251'=>'module-2021',
'acsModule20251style'=>'width: 20%;',
'acsModule20252'=>'module-2002',
'acsModule20252style'=>'width: 80%;',
'acsModule2025ShadowSize'=>'5',
'acsModule2025ShadowBlur'=>'5',
'acsModule2025Comment'=>'Bloc central de la page plan',
'acsModule2030Use'=>'oui',
'acsModule2030Orientation'=>'vertical',
'acsModule20301'=>'module-1',
'acsModule20302'=>'module-2035',
'acsModule20308'=>'module-3',
'acsModule2030ShadowSize'=>'5',
'acsModule2030ShadowBlur'=>'5',
'acsModule2030Comment'=>'Page sites',
'acsModule2031Use'=>'oui',
'acsModule2031Orientation'=>'vertical',
'acsModule2031Left'=>'=acsModule2001Left',
'acsModule2031Right'=>'=acsModule2001Right',
'acsModule20311'=>'recherche',
'acsModule20312'=>'rubnav',
'acsModule20313'=>'auteurs',
'acsModule20314'=>'forums',
'acsModule2031ShadowSize'=>'5',
'acsModule2031ShadowBlur'=>'5',
'acsModule2031Comment'=>'Colonne gauche de la page sites',
'acsModule2035Use'=>'oui',
'acsModule2035Orientation'=>'horizontal',
'acsModule2035Right'=>'=acsModule2025Right',
'acsModule2035Top'=>'=acsModule2005Top',
'acsModule20351'=>'module-2031',
'acsModule20351style'=>'=acsModule20251style',
'acsModule20352style'=>'=acsModule20252style',
'acsModule2035ShadowSize'=>'5',
'acsModule2035ShadowBlur'=>'5',
'acsModule2035Comment'=>'Bloc central de la page sites (2 colonnes)',
'acsOngletsUse'=>'oui',
'acsOngletsFondColor'=>'#ffffff',
'acsOngletsBordColor'=>'#dfdfdf',
'acsOngletsCouleurInactif'=>'#efefef',
'acsOngletsCouleurSurvol'=>'#ffffff',
'acsOnglets1'=>'sommaire',
'acsOnglets2'=>'resume',
'acsOnglets3'=>'plan',
'acsOnglets4'=>'sites',
'acsOngletschoix4'=>'oui',
'acsOnglets5'=>'forums',
'acsOngletschoix5'=>'non',
'acsOngletsPublier'=>'oui',
'acsOursUse'=>'oui',
'acsOursLienCopyright'=>'oui',
'acsOursLienRSS'=>'oui',
'acsOursLienResume'=>'oui',
'acsOursLienRefus'=>'non',
'acsOursLienACS'=>'oui',
'acsOursLienSPIP'=>'oui',
'acsOursStats'=>'oui',
'acsRechercheUse'=>'oui',
'acsRechercheTitreFond'=>'=acsRubnavTitreFond',
'acsRechercheTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsRechercheBord'=>'=acsRubnavBord',
'acsRechercheFond'=>'=acsRubnavFond',
'acsRechercheInput'=>'#ffffff',
'acsRubnavUse'=>'oui',
'acsRubnavFond'=>'#f4f4ff',
'acsRubnavFond2'=>'#efefff',
'acsRubnavFond3'=>'#e4e4ff',
'acsRubnavFond4'=>'#dfdfef',
'acsRubnavFond5'=>'#cacaff',
'acsRubnavFond6'=>'#c4c4ef',
'acsRubnavFondHover'=>'#f8f8df',
'acsRubnavTitre'=>'oui',
'acsRubnavTitreFond'=>'#eef5f7',
'acsRubnavTitreFondImage'=>'titrefond_00.png',
'acsRubnavBord'=>'a:3:{s:5:"Width";s:3:"1px";s:5:"Style";s:5:"inset";s:5:"Color";s:7:"#ffffff";}',
'acsRubnavSep'=>'#dfdfdf',
'acsRubnavDeplierHaut'=>'deplierhaut.gif',
'acsRubnavDeplierHautOver'=>'deplierhauton.gif',
'acsRubnavDeplierHaut_rtl'=>'deplierhaut_rtl.gif',
'acsRubnavDeplierHautOver_rtl'=>'deplierhauton_rtl.gif',
'acsRubnavDeplierBas'=>'deplierbas.gif',
'acsRubnavDeplierBasOver'=>'deplierbason.gif',
'acsRubriquesUse'=>'oui',
'acsRubriquesTitreFond'=>'=acsRubnavTitreFond',
'acsRubriquesTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsRubriquesFond'=>'=acsRubnavFond',
'acsSyndicUse'=>'oui',
'acsSyndicTitreFond'=>'=acsRubnavTitreFond',
'acsSyndicTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsSyndicFond'=>'=acsRubnavFond',
'acsTagsUse'=>'oui',
'acsTagsFond'=>'=acsRubnavFond',
'acsTagsTitre'=>'=acsRubnavTitre',
'acsTagsTitreFond'=>'=acsRubnavTitreFond',
'acsTagsTitreFondImage'=>'=acsRubnavTitreFondImage',
'acsTagsSep'=>'=acsRubnavSep',
'acsVideoUse'=>'oui',
);
?>