<?php
#              ACS
#          (Plugin Spip)
#     http://acs.geomaticien.org
#
# Copyright Daniel FAIVRE, 2007-2009
# Copyleft: licence GPL - Cf. LICENCES.txt
#
/**
 *  ACS model default values
 * On initialise les valeurs des variables du modèle 
 */
$def = array(
	'acsAgendaUse' => 'oui',
	'acsAgendaTitreFondColor' => '=acsRubnavTitreFond',
	'acsAgendaTitreFondImage' => '=acsRubnavTitreFondImage',
	'acsAgendaBordColor' => '=acsRubnavBordColor',
	'acsAgendaBordWidth' => '=acsRubnavBordWidth',
	'acsAgendaBordStyle' => '=acsRubnavBordStyle',
	'acsAgendaThisMonth' => '=acsRubnavFond', 
	'acsArticlesUse' => 'oui',
	'acsArticlesTabBordColor' => '#cfcfcf',
	'acsArticlesTabBordWidth' => 'thin',
	'acsArticlesTabBordStyle' => 'solid',
	'acsArticlesTabFirst' => '#dfe5ef',
	'acsArticlesTabOdd' => '#e4dfef',
	'acsArticlesTabEven' => '#dfdfef',
	'acsAudioUse' => 'oui',
	'acsAudioTitreImage' => '=acsRubnavTitreFondImage',
	'acsAudioBord' => 'acsRubnavBordColor',
 	'acsAudioBordWidth' => '=acsRubnavBordWidth',
	'acsAudioBordStyle' => '=acsRubnavBordStyle', 
	'acsAuteursUse' => 'oui',
	'acsBanniereUse' => 'oui',
	'acsBanniereUseLogo' => 'non',
	'acsBandeauUse' => 'oui',
	'acsBandeauContenu' => '<a href="http://acs.geomaticien.org">ACS</a>: pour configurer ce site, <a href="ecrire/?exec=acs&amp;onglet=composants&amp;composant=fond">cliquez ici</a>.',
	'acsFondUse' => 'oui',
	'acsFondFavicon' => 'favicon.ico',
	'acsFondColor' => '#f4f4f4',
	'acsFondText' => '#002200',
	'acsFondLink' => '#00008d',
	'acsFondLinkHover' => '#0000f4',
	'acsForumsUse' => 'oui',
	'acsEditoUse' => 'oui',
	'acsOngletsUse' => 'oui',
	'acsOnglets1' => 'sommaire',
	'acsOnglets2' => 'resume',
	'acsOnglets3' => 'plan',
	'acsOnglets4' => 'sites',
	'acsOngletschoix5' => 'non',
	'acsOnglets5' => 'forums',
	'acsOngletsFondColor' => '#ffffff',
	'acsOngletsBordColor' => '#dfdfdf',
	'acsOngletsCouleurInactif' => '#efefef',
	'acsOngletsCouleurSurvol' => '#ffffff',
	'acsOursUse' => 'oui',
	'acsRechercheUse' => 'oui',
	'acsRubnavUse' => 'oui',
	'acsRubnavFond' => '#f4f4ff',
	'acsRubnavFond2' => '#efefff',
	'acsRubnavFond3' => '#e4e4ff',
	'acsRubnavFondHover' => '#f8f8df',
	'acsRubnavSep' => '#dfdfdf',
	'acsSyndicUse' => 'oui',
	'acsTagsUse' => 'oui',
	'acsVideoUse' => 'oui',

	'acsModuleUse' => 'oui',
	'acsModule1Use' => 'oui',
	'acsModule11' => 'banniere',
	'acsModule12' => 'bandeau',
	'acsModule3Use' => 'oui',
	'acsModule32' => 'ours',
	'acsModule21Use' => 'oui',
	'acsModule21Left' => '10px',
	'acsModule21Right' => '10px',
	'acsModule211' => 'recherche',
	'acsModule212' => 'rubnav',
	'acsModule22Use' => 'oui',
	'acsModule22Left' => '10px',
	'acsModule22Right' => '10px',
	'acsModule221' => 'recherche',
	'acsModule222' => 'rubnav',
	'acsModule23Use' => 'oui',
	'acsModule23Left' => '10px',
	'acsModule23Right' => '10px',
	'acsModule231' => 'recherche',
	'acsModule232' => 'rubnav',
  'acsModule233' => 'auteurs',
  'acsModule234' => 'forums',
  'acsModule235' => 'keys',
	'acsModule25Use' => 'oui',
	'acsModule25Left' => '10px',
	'acsModule25Right' => '10px',
	'acsModule251' => 'agenda',
	'acsModule252' => 'tags',
	'acsModule26Use' => 'oui',
	'acsModule26Left' => '10px',
	'acsModule26Right' => '10px',
	'acsModule261' => 'agenda',

	'acsDerniereModif' => time(),
	'acsModel' => 'cat',

);
?>