<?php
// This is a SPIP language file  --  Ceci est un fichier langue de SPIP
// extrait automatiquement de http://trad.spip.net/tradlang_module/seo?lang_cible=en
// ** ne pas modifier le fichier **

if (!defined('_ECRIRE_INC_VERSION')) return;

$GLOBALS[$GLOBALS['idx_lang']] = array(

	// S
	'S.E.O' => 'SEO',

	// A
	'alexa' => 'Alexa',
	'alexa_activate' => 'Activate Alexa',
	'alexa_id' => 'Website Alexa\'s ID',

	// B
	'bing_webmaster' => 'Bing Webmaster Tools',
	'bing_webmaster_activate' => 'Enable Bing Webmaster Tools',
	'bing_webmaster_id' => 'Meta Code verification',

	// C
	'canonical_url' => 'Canonical URL',
	'canonical_url_activate' => 'Activate Canonical URL meta',

	// E
	'explication_description' => 'Il est conseillé que la longueur soit inférieure ou égale à 160 caractères.', # NEW
	'explication_title' => 'Il est conseillé que la longueur soit comprise entre 5 et 70 caractères.', # NEW

	// F
	'forcer_squelette_descriptif' => 'SEO metas are prioritary to the metas generated by the skeleton',
	'forcer_squelette_label' => 'Load metas for all skeletons',

	// G
	'google_analytics' => 'Google Analytics',
	'google_analytics_activate' => 'Activate Google Analytics',
	'google_analytics_id' => 'Google Analytics web property ID',
	'google_webmaster_tools' => 'Google Webmaster Tools',
	'google_webmaster_tools_activate' => 'Activate Google Webmaster Tools',
	'google_webmaster_tools_id' => 'Meta Code verification',

	// I
	'info_count_max' => 'Caractères pour atteindre la limite optimale : ', # NEW
	'insert_head' => 'Automatic insertion in #INSERT_HEAD',
	'insert_head_activate' => 'Activate automatic insertion',
	'insert_head_descriptif' => 'Automatic insertion of SEO configuration in the <head>',

	// M
	'meta_author' => 'Author:',
	'meta_copyright' => 'Copyright:',
	'meta_description' => 'Description:',
	'meta_keywords' => 'Keywords:',
	'meta_page_description_sommaire_value' => 'Page Description Value + Home Page Meta Value',
	'meta_page_description_value' => 'Page Description Value',
	'meta_page_title_sommaire_value' => 'Page Title Value + Home Page Meta Value',
	'meta_page_title_value' => 'Page Title Value',
	'meta_robots' => 'Robots:',
	'meta_sommaire_value' => 'Home Page Meta Value',
	'meta_tags' => 'Meta Tags',
	'meta_tags_activate' => 'Activate editorial meta tags',
	'meta_tags_default' => 'Defaults values for meta tags (for articles and sections)',
	'meta_tags_edit_activate' => 'Activate meta tags editing in sections and articles',
	'meta_tags_editing' => 'Meta tags editing',
	'meta_tags_sommaire' => 'Summary meta tags value (home page)',
	'meta_title' => 'Title:',

	// S
	'seo' => 'Search Engine Optimisation'
);

?>
