<?php
// This is a SPIP language file  --  Ceci est un fichier langue de SPIP
// extrait automatiquement de http://trad.spip.net/tradlang_module/paquet-thumbsites?lang_cible=en
// ** ne pas modifier le fichier **

if (!defined('_ECRIRE_INC_VERSION')) return;

$GLOBALS[$GLOBALS['idx_lang']] = array(

	// T
	'thumbsites_description' => 'Thumbsites provides a system of site screenshots capture generated by dedicated servers. The plugin provides tags, filters and templates to display a thumbnail for a given site. This plugin also manages a cache that overcomes the frequent unavailability of servers and speed displays. Configuration is available in the private space.',
	'thumbsites_slogan' => 'A thumbnail for your referenced sites'
);

?>
