-
  saisie: 'input'
  options:
    explication: "<:vimeo:client_data:>"
    nom: 'client_id'
    label: '<:vimeo:client_id:>'
-
  saisie: 'input'
  options:
    nom: 'client_secret'
    label: '<:vimeo:client_secret:>'        
-
  saisie: 'input'
  options:
    nom: 'user_vimeo'
    label: '<:vimeo:user_vimeo:>'
    explication: '<:vimeo:user_vimeo_explication:>'
-
  saisie: 'radio'
  options:
    nom: 'profil'
    label: '<:vimeo:profil:>'
    obligatoire: 'oui'
    defaut: 'rien'
    datas: 
      new: '<:vimeo:profil_new:>'
      auteur: '<:vimeo:profil_auteur:>'
      rien: '<:vimeo:profil_rien:>'
-
  saisie: 'auteurs'
  options:
    nom: 'id_auteur'
    label: '<:vimeo:id_auteur:>'
    afficher_si: '@profil@=="auteur"'
-
  saisie: 'statuts_auteurs'
  options:
    nom: 'profil_auteur_statut'
    label: '<:vimeo:profil_auteur_statut:>'
    afficher_si: '@profil@=="new"'
-
  saisie: 'oui_non'
  options:
    nom: 'liaison_auteur'
    label: '<:vimeo:liaison_auteur:>'
    afficher_si: '@profil@=="new" || @profil@=="auteur"'
-
  saisie: 'oui_non'
  options:
    nom: 'albums'
    label: '<:vimeo:albums:>'
-
  saisie: 'groupe_mots'
  options:
    nom: 'id_groupe_albums'
    label: '<:vimeo:id_groupe_albums:>'
    explication: '<:vimeo:id_groupe_albums_explication:>'
    afficher_si: '@albums@ == "on"'
-
  saisie: 'oui_non'
  options:
    nom: 'archives'
    label: '<:vimeo:archives:>'
-
  saisie: 'groupe_mots'
  options:
    nom: 'id_groupe_archives'
    label: '<:vimeo:id_groupe_albums:>'
    explication: '<:vimeo:id_groupe_explication_archives:>'
    afficher_si: '@archives@ == "on"'
-
  saisie: 'input'
  options:
    nom: 'vimeo_statut'
    label: '<:vimeo:vimeo_statut:>'
    defaut: 'publie'