<?php
/**
 * Plugin Pays pour Spip 3.0
 * Licence GPL
 * Auteur Organisation Internationale de Normalisation http://www.iso.org/iso/fr/country_codes/iso_3166_code_lists.htm
 * Cedric Morin et Collectif SPIP pour version spip_geo_pays
 * Portage sous SPIP par Cyril MARION - Ateliers CYM http://www.cym.fr
 *
 */
if (!defined("_ECRIRE_INC_VERSION")) return;

function peupler_base_pays() {

    sql_insertq_multi('spip_pays', array(
        array('id_pays'=>'1','code'=>'AF','code_num'=>4,'code_alpha3'=>'AFG','nom'=>'<multi>[fr]Afghanistan[en]Afghanistan[de]Afghanistan[es]Afganistán[it]Afghanistan[nl]Afghanistan[pt]Afeganistão</multi>'),
        array('id_pays'=>'2','code'=>'ZA','code_num'=>710,'code_alpha3'=>'ZAF','nom'=>'<multi>[fr]Afrique du Sud[en]South Africa[de]Süd-Afrika[es]Sudáfrica[it]Sud Africa[nl]Zuid-Afrika[pt]áfrica do Sul</multi>'),
        array('id_pays'=>'3','code'=>'AX','code_num'=>248,'code_alpha3'=>'ALA','nom'=>'<multi>[fr]Åland[en]Åland[de]Åland[es]Åland[it]Åland[nl]Åland[pt]Åland</multi>'),
        array('id_pays'=>'4','code'=>'AL','code_num'=>8,'code_alpha3'=>'ALB','nom'=>'<multi>[fr]Albanie[en]Albania[de]Albanien[es]Albania[it]Albania[nl]Albanië[pt]Albânia</multi>'),
        array('id_pays'=>'5','code'=>'DZ','code_num'=>12,'code_alpha3'=>'DZA','nom'=>'<multi>[fr]Algérie[en]Algeria[de]Algerien[es]Argelia[it]Algeria[nl]Algerije[pt]Argélia</multi>'),
        array('id_pays'=>'6','code'=>'DE','code_num'=>276,'code_alpha3'=>'DEU','nom'=>'<multi>[fr]Allemagne[en]Germany[de]Deutschland[es]Alemania[it]Germania[nl]Duitsland[pt]Alemanha</multi>'),
        array('id_pays'=>'7','code'=>'AD','code_num'=>20,'code_alpha3'=>'AND','nom'=>'<multi>[fr]Andorre[en]Andorra[de]Andorra[es]Andorra[it]Andorra[nl]Andorra[pt]Andorra</multi>'),
        array('id_pays'=>'8','code'=>'AO','code_num'=>24,'code_alpha3'=>'AGO','nom'=>'<multi>[fr]Angola[en]Angola[de]Angola[es]Angola[it]Angola[nl]Angola[pt]Angola</multi>'),
        array('id_pays'=>'9','code'=>'AI','code_num'=>660,'code_alpha3'=>'AIA','nom'=>'<multi>[fr]Anguilla[en]Anguilla[de]Anguilla[es]Anguila[it]Anguilla[nl]Anguilla[pt]Anguilla</multi>'),
        array('id_pays'=>'10','code'=>'AQ','code_num'=>10,'code_alpha3'=>'ATA','nom'=>'<multi>[fr]Antarctique[en]Antarctica[de]Antarktis[es]Antártida[it]Antartide[pt]Antártica</multi>'),
        array('id_pays'=>'11','code'=>'AG','code_num'=>28,'code_alpha3'=>'ATG','nom'=>'<multi>[fr]Antigua-et-Barbuda[en]Antigua and Barbuda[de]Antigua und Barbuda[es]Antigua y Barbuda[it]Antigua e Barbuda[nl]Antigua en Barbuda[pt]Antigua e Barbuda</multi>'),
        array('id_pays'=>'12','code'=>'AN','code_num'=>530,'code_alpha3'=>'ANT','nom'=>'<multi>[fr]Antilles néerlandaises[en]Netherlands Antilles[de]Niederländische Antillen[es]Antillas Neerlandesas[it]Antille olandesi[nl]Nederlandse Antillen[pt]Antilhas Holandesas</multi>'),
        array('id_pays'=>'13','code'=>'SA','code_num'=>682,'code_alpha3'=>'SAU','nom'=>'<multi>[fr]Arabie saoudite[en]Saudi Arabia[de]Saudi-Arabien[es]Arabia Saudita[it]Arabia Saudita[nl]Saoedi-Arabië[pt]Arábia Saudita</multi>'),
        array('id_pays'=>'14','code'=>'AR','code_num'=>32,'code_alpha3'=>'ARG','nom'=>'<multi>[fr]Argentine[en]Argentina[de]Argentinien[es]Argentina[it]Argentina[nl]Argentinië[pt]Argentina</multi>'),
        array('id_pays'=>'15','code'=>'AM','code_num'=>51,'code_alpha3'=>'ARM','nom'=>'<multi>[fr]Arménie[en]Armenia[de]Armenien[es]Armenia[it]Armenia[nl]Armenië[pt]Arménia</multi>'),
        array('id_pays'=>'16','code'=>'AW','code_num'=>533,'code_alpha3'=>'ABW','nom'=>'<multi>[fr]Aruba[en]Aruba[de]Aruba[es]Aruba[it]Aruba[nl]Aruba[pt]Aruba</multi>'),
        array('id_pays'=>'17','code'=>'AU','code_num'=>36,'code_alpha3'=>'AUS','nom'=>'<multi>[fr]Australie[en]Australia[de]Australien[es]Australia[it]Australia[nl]Australië[pt]Austrália</multi>'),
        array('id_pays'=>'18','code'=>'AT','code_num'=>40,'code_alpha3'=>'AUT','nom'=>'<multi>[fr]Autriche[en]Austria[de]Österreich[es]Austria[it]Austria[nl]Oostenrijk[pt]áustria</multi>'),
        array('id_pays'=>'19','code'=>'AZ','code_num'=>31,'code_alpha3'=>'AZE','nom'=>'<multi>[fr]Azerbaïdjan[en]Azerbaijan[de]Aserbaidschan[es]Azerbaiyán[it]Azerbaigian[nl]Azerbeidzjan[pt]Azerbaijão</multi>'),
        array('id_pays'=>'20','code'=>'BS','code_num'=>44,'code_alpha3'=>'BHS','nom'=>'<multi>[fr]Bahamas[en]Bahamas[de]Bahamas[es]Bahamas[it]Bahamas[nl]Bahama\'s[pt]Bahamas</multi>'),
        array('id_pays'=>'21','code'=>'BH','code_num'=>48,'code_alpha3'=>'BHR','nom'=>'<multi>[fr]Bahreïn[en]Bahrain[de]Bahrain[es]Bahrein[it]Bahrein[nl]Bahrein[pt]Bahrein</multi>'),
        array('id_pays'=>'22','code'=>'BD','code_num'=>50,'code_alpha3'=>'BGD','nom'=>'<multi>[fr]Bangladesh[en]Bangladesh[de]Bangladesch[es]Bangladesh[it]Bangladesh[nl]Bangladesh[pt]Bangladesh</multi>'),
        array('id_pays'=>'23','code'=>'BB','code_num'=>52,'code_alpha3'=>'BRB','nom'=>'<multi>[fr]Barbade[en]Barbados[de]Barbados[es]Barbados[it]Barbados[nl]Barbados[pt]Barbados</multi>'),
        array('id_pays'=>'24','code'=>'BE','code_num'=>56,'code_alpha3'=>'BEL','nom'=>'<multi>[fr]Belgique[en]Belgium[de]Belgien[es]Bélgica[it]Belgio[nl]België[pt]Bélgica</multi>'),
        array('id_pays'=>'25','code'=>'BZ','code_num'=>84,'code_alpha3'=>'BLZ','nom'=>'<multi>[fr]Belize[en]Belize[de]Belize[es]Belice[it]Belize[nl]Belize[pt]Belize</multi>'),
        array('id_pays'=>'26','code'=>'BJ','code_num'=>204,'code_alpha3'=>'BEN','nom'=>'<multi>[fr]Bénin[en]Benin[de]Benin[es]Benin[it]Benin[nl]Benin[pt]Benin</multi>'),
        array('id_pays'=>'27','code'=>'BM','code_num'=>60,'code_alpha3'=>'BMU','nom'=>'<multi>[fr]Bermudes[en]Bermuda[de]Bermuda[es]Bermudas[it]Bermuda[nl]Bermuda[pt]Bermudas</multi>'),
        array('id_pays'=>'28','code'=>'BT','code_num'=>64,'code_alpha3'=>'BTN','nom'=>'<multi>[fr]Bhoutan[en]Bhutan[de]Bhutan[es]Bután[it]Bhutan[nl]Bhutan[pt]Butão</multi>'),
        array('id_pays'=>'29','code'=>'BY','code_num'=>112,'code_alpha3'=>'BLR','nom'=>'<multi>[fr]Biélorussie[en]Belarus[de]Wei§russland[es]Bielorrusia[it]Bielorussia[nl]Wit-Rusland[pt]Belarus</multi>'),
        array('id_pays'=>'30','code'=>'MM','code_num'=>104,'code_alpha3'=>'MMR','nom'=>'<multi>[fr]Birmanie[en]Burma[de]Birma[es]Birmania[it]Birmania[nl]Myanmar[pt]Birmânia</multi>'),
        array('id_pays'=>'31','code'=>'BO','code_num'=>68,'code_alpha3'=>'BOL','nom'=>'<multi>[fr]Bolivie[en]Bolivia[de]Bolivien[es]Bolivia[it]Bolivia[nl]Bolivia[pt]Bolívia</multi>'),
        array('id_pays'=>'32','code'=>'BA','code_num'=>70,'code_alpha3'=>'BIH','nom'=>'<multi>[fr]Bosnie-Herzégovine[en]Bosnia and Herzegovina[de]Bosnien-Herzegowina[es]Bosnia y Herzegovina[it]Bosnia-Erzegovina[nl]Bosnië en Herzegovina[pt]Bósnia e Herzegovina</multi>'),
        array('id_pays'=>'33','code'=>'BW','code_num'=>72,'code_alpha3'=>'BWA','nom'=>'<multi>[fr]Botswana[en]Botswana[de]Botswana[es]Botswana[it]Botswana[nl]Botswana[pt]Botsuana</multi>'),
        array('id_pays'=>'34','code'=>'BR','code_num'=>76,'code_alpha3'=>'BRA','nom'=>'<multi>[fr]Brésil[en]Brazil[de]Brasilien[es]Brasil[it]Brasile[nl]Brazilië[pt]Brasil</multi>'),
        array('id_pays'=>'35','code'=>'BN','code_num'=>96,'code_alpha3'=>'BRN','nom'=>'<multi>[fr]Brunei[en]Brunei[de]Brunei[es]Brunei[it]Brunei[nl]Brunei[pt]Brunei</multi>'),
        array('id_pays'=>'36','code'=>'BG','code_num'=>100,'code_alpha3'=>'BGR','nom'=>'<multi>[fr]Bulgarie[en]Bulgaria[de]Bulgarien[es]Bulgaria[it]Bulgaria[nl]Bulgarije[pt]Bulgária</multi>'),
        array('id_pays'=>'37','code'=>'BF','code_num'=>854,'code_alpha3'=>'BFA','nom'=>'<multi>[fr]Burkina Faso[en]Burkina Faso[de]Burkina Faso[es]Burkina Faso[it]Burkina Faso[nl]Burkina Faso[pt]Burkina Faso</multi>'),
        array('id_pays'=>'38','code'=>'BI','code_num'=>108,'code_alpha3'=>'BDI','nom'=>'<multi>[fr]Burundi[en]Burundi[de]Burundi[es]Burundi[it]Burundi[nl]Burundi[pt]Burundi</multi>'),
        array('id_pays'=>'39','code'=>'KH','code_num'=>116,'code_alpha3'=>'KHM','nom'=>'<multi>[fr]Cambodge[en]Cambodia[de]Kambodscha[es]Camboya[it]Cambogia[nl]Cambodja[pt]Camboja</multi>'),
        array('id_pays'=>'40','code'=>'CM','code_num'=>120,'code_alpha3'=>'CMR','nom'=>'<multi>[fr]Cameroun[en]Cameroon[de]Kamerun[es]Camerún[it]Camerun[nl]Kameroen[pt]Camarões</multi>'),
        array('id_pays'=>'41','code'=>'CA','code_num'=>124,'code_alpha3'=>'CAN','nom'=>'<multi>[fr]Canada[en]Canada[de]Kanada[es]Canadá[it]Canada[nl]Canada[pt]Canadá</multi>'),
        array('id_pays'=>'42','code'=>'CV','code_num'=>132,'code_alpha3'=>'CPV','nom'=>'<multi>[fr]Cap-Vert[en]Cape Verde[de]Kap Verde[es]Cabo Verde[it]Capo Verde[nl]Kaapverdië[pt]Cabo Verde</multi>'),
        array('id_pays'=>'43','code'=>'CF','code_num'=>140,'code_alpha3'=>'CAF','nom'=>'<multi>[fr]Centrafrique[en]Central African Republic[de]Zentralafrika[es]Rep. Centroafricana[it]Repubblica Centrafricana[nl]Centraal-Afrikaanse Republiek[pt]Repùblica Centro-Africana</multi>'),
        array('id_pays'=>'44','code'=>'CL','code_num'=>152,'code_alpha3'=>'CHL','nom'=>'<multi>[fr]Chili[en]Chile[de]Chile[es]Chile[it]Cile[nl]Chili[pt]Chile</multi>'),
        array('id_pays'=>'45','code'=>'CN','code_num'=>156,'code_alpha3'=>'CHN','nom'=>'<multi>[fr]Chine[en]China[de]China[es]China[it]Cina[nl]China[pt]China</multi>'),
        array('id_pays'=>'46','code'=>'CY','code_num'=>196,'code_alpha3'=>'CYP','nom'=>'<multi>[fr]Chypre[en]Cyprus[de]Zypern[es]Chipre[it]Cipro[nl]Cyprus[pt]Chipre</multi>'),
        array('id_pays'=>'47','code'=>'CO','code_num'=>170,'code_alpha3'=>'COL','nom'=>'<multi>[fr]Colombie[en]Colombia[de]Kolumbien[es]Colombia[it]Colombia[nl]Colombia[pt]Colômbia</multi>'),
        array('id_pays'=>'48','code'=>'KM','code_num'=>174,'code_alpha3'=>'COM','nom'=>'<multi>[fr]Comores[en]Comoros[de]Komoren[es]Comoras[it]Comore[nl]Comoren[pt]Comores</multi>'),
        array('id_pays'=>'49','code'=>'CG','code_num'=>178,'code_alpha3'=>'COG','nom'=>'<multi>[fr]Congo-Brazzaville[en]Congo-Brazzaville[de]Kongo-Brazzaville[es]Congo-Brazzaville[it]Congo-Brazzaville[nl]Congo-Brazzaville[pt]Congo-Brazzaville</multi>'),
        array('id_pays'=>'50','code'=>'CD','code_num'=>180,'code_alpha3'=>'COD','nom'=>'<multi>[fr]Congo-Kinshasa[en]Congo-Kinshasa[de]Kongo-Kinshasa[es]Congo-Kinshasa[it]Congo-Kinshasa[nl]Congo-Kinshasa[pt]Congo-Kinshasa</multi>'),
        array('id_pays'=>'51','code'=>'KP','code_num'=>408,'code_alpha3'=>'PRK','nom'=>'<multi>[fr]Corée du Nord[en]North Korea[de]Nordkorea[es]Corea del Norte[it]Corea del Nord[nl]Noord-Korea[pt]Coreia do Norte</multi>'),
        array('id_pays'=>'52','code'=>'KR','code_num'=>410,'code_alpha3'=>'KOR','nom'=>'<multi>[fr]Corée du Sud[en]South Korea[de]Südkorea[es]Corea del Sur[it]Corea del Sud[nl]Zuid-Korea[pt]Coréia do Sul</multi>'),
        array('id_pays'=>'53','code'=>'CR','code_num'=>188,'code_alpha3'=>'CRI','nom'=>'<multi>[fr]Costa Rica[en]Costa Rica[de]Costa Rica[es]Costa Rica[it]Costa Rica[nl]Costa Rica[pt]Costa Rica</multi>'),
        array('id_pays'=>'54','code'=>'CI','code_num'=>384,'code_alpha3'=>'CIV','nom'=>'<multi>[fr]Côte d\'Ivoire[en]Côte d\'Ivoire[de]Côte d\'Ivoire[es]Côte d\'Ivoire[it]Costa d\'Avorio[nl]Ivoorkust[pt]Costa do Marfim</multi>'),
        array('id_pays'=>'55','code'=>'HR','code_num'=>191,'code_alpha3'=>'HRV','nom'=>'<multi>[fr]Croatie[en]Croatia[de]Kroatien[es]Croacia[it]Croazia[nl]Kroatië[pt]Croácia</multi>'),
        array('id_pays'=>'56','code'=>'CU','code_num'=>192,'code_alpha3'=>'CUB','nom'=>'<multi>[fr]Cuba[en]Cuba[de]Kuba[es]Cuba[it]Cuba[nl]Cuba[pt]Cuba</multi>'),
        array('id_pays'=>'57','code'=>'DK','code_num'=>208,'code_alpha3'=>'DNK','nom'=>'<multi>[fr]Danemark[en]Denmark[de]Dänemark[es]Dinamarca[it]Danimarca[nl]Denemarken[pt]Dinamarca</multi>'),
        array('id_pays'=>'58','code'=>'DJ','code_num'=>262,'code_alpha3'=>'DJI','nom'=>'<multi>[fr]Djibouti[en]Djibouti[de]Dschibuti[es]Djibouti[it]Gibuti[nl]Djibouti[pt]Djibouti</multi>'),
        array('id_pays'=>'59','code'=>'DM','code_num'=>212,'code_alpha3'=>'DMA','nom'=>'<multi>[fr]Dominique[en]Dominica[de]Dominica[es]Dominica[it]Dominica[nl]Dominica[pt]Dominica</multi>'),
        array('id_pays'=>'60','code'=>'EG','code_num'=>818,'code_alpha3'=>'EGY','nom'=>'<multi>[fr]Égypte[en]Egypt[de]ägypten[es]Egipto[it]Egitto[nl]Egypte[pt]Egito</multi>'),
        array('id_pays'=>'61','code'=>'AE','code_num'=>784,'code_alpha3'=>'ARE','nom'=>'<multi>[fr]Émirats arabes unis[en]United Arab Emirates[de]Vereinigte Arabische Emirate[es]Emiratos árabes Unidos[it]Emirati Arabi Uniti[nl]Verenigde Arabische Emiraten[pt]Emirados árabes Unidos</multi>'),
        array('id_pays'=>'62','code'=>'EC','code_num'=>218,'code_alpha3'=>'ECU','nom'=>'<multi>[fr]Équateur[en]Ecuador[de]Ecuador[es]Ecuador[it]Ecuador[nl]Ecuador[pt]Equador</multi>'),
        array('id_pays'=>'63','code'=>'ER','code_num'=>232,'code_alpha3'=>'ERI','nom'=>'<multi>[fr]Érythrée[en]Eritrea[de]Eritrea[es]Eritrea[it]Eritrea[nl]Eritrea[pt]Eritreia</multi>'),
        array('id_pays'=>'64','code'=>'ES','code_num'=>724,'code_alpha3'=>'ESP','nom'=>'<multi>[fr]Espagne[en]Spain[de]Spanien[es]España[it]Spagna[nl]Spanje[pt]Espanha</multi>'),
        array('id_pays'=>'65','code'=>'EE','code_num'=>233,'code_alpha3'=>'EST','nom'=>'<multi>[fr]Estonie[en]Estonia[de]Estland[es]Estonia[it]Estonia[nl]Estland[pt]Estónia</multi>'),
        array('id_pays'=>'66','code'=>'US','code_num'=>840,'code_alpha3'=>'USA','nom'=>'<multi>[fr]États-Unis[en]United States[de]Vereinigte Staaten[es]Estados Unidos[it]Stati Uniti[nl]Verenigde Staten[pt]Estados Unidos</multi>'),
        array('id_pays'=>'67','code'=>'ET','code_num'=>231,'code_alpha3'=>'ETH','nom'=>'<multi>[fr]Éthiopie[en]Ethiopia[de]äthiopien[es]Etiopía[it]Etiopia[nl]Ethiopië[pt]Etiópia</multi>'),
        array('id_pays'=>'68','code'=>'FJ','code_num'=>242,'code_alpha3'=>'FJI','nom'=>'<multi>[fr]Fidji[en]Fiji[de]Fidschi[es]Fiji[it]Figi[nl]Fiji[pt]Fiji</multi>'),
        array('id_pays'=>'69','code'=>'FI','code_num'=>246,'code_alpha3'=>'FIN','nom'=>'<multi>[fr]Finlande[en]Finland[de]Finnland[es]Finlandia[it]Finlandia[nl]Finland[pt]Finlândia</multi>'),
        array('id_pays'=>'70','code'=>'FR','code_num'=>250,'code_alpha3'=>'FRA','nom'=>'<multi>[fr]France[en]France[de]Frankreich[es]Francia[it]Francia[nl]Frankrijk[pt]França</multi>'),
        array('id_pays'=>'71','code'=>'GA','code_num'=>266,'code_alpha3'=>'GAB','nom'=>'<multi>[fr]Gabon[en]Gabon[de]Gabun[es]Gabón[it]Gabon[nl]Gabon[pt]Gabão</multi>'),
        array('id_pays'=>'72','code'=>'GM','code_num'=>270,'code_alpha3'=>'GMB','nom'=>'<multi>[fr]Gambie[en]Gambia[de]Gambia[es]Gambia[it]Gambia[nl]Gambia[pt]Gâmbia</multi>'),
        array('id_pays'=>'73','code'=>'GE','code_num'=>268,'code_alpha3'=>'GEO','nom'=>'<multi>[fr]Géorgie[en]Georgia[de]Georgien[es]Georgia[it]Georgia[nl]Georgië[pt]Geórgia</multi>'),
        array('id_pays'=>'74','code'=>'GS','code_num'=>239,'code_alpha3'=>'SGS','nom'=>'<multi>[fr]Géorgie du Sud et les îles Sandwich du Sud[en]South Georgia and the South Sandwich Islands[de]Süd-Georgien und die Süd-Sandwich-Inseln[es]Georgia del Sur y las Islas Sandwich del Sur[it]Georgia del Sud e il Sud e Isole Sandwich[nl]Zuid-Georgië en de Zuidelijke Sandwicheilanden[pt]Geórgia do Sul e Sandwich do Sul Ilhas</multi>'),
        array('id_pays'=>'75','code'=>'GH','code_num'=>288,'code_alpha3'=>'GHA','nom'=>'<multi>[fr]Ghana[en]Ghana[de]Ghana[es]Ghana[it]Ghana[nl]Ghana[pt]Gana</multi>'),
        array('id_pays'=>'76','code'=>'GI','code_num'=>292,'code_alpha3'=>'GIB','nom'=>'<multi>[fr]Gibraltar[en]Gibraltar[de]Gibraltar[es]Gibraltar[it]Gibilterra[nl]Gibraltar[pt]Gibraltar</multi>'),
        array('id_pays'=>'77','code'=>'GR','code_num'=>300,'code_alpha3'=>'GRC','nom'=>'<multi>[fr]Grèce[en]Greece[de]Griechenland[es]Grecia[it]Grecia[nl]Griekenland[pt]Grécia</multi>'),
        array('id_pays'=>'78','code'=>'GD','code_num'=>308,'code_alpha3'=>'GRD','nom'=>'<multi>[fr]Grenade[en]Grenada[de]Granada[es]Granada[it]Grenada[nl]Grenada[pt]Grenada</multi>'),
        array('id_pays'=>'79','code'=>'GL','code_num'=>304,'code_alpha3'=>'GRL','nom'=>'<multi>[fr]Groenland[en]Greenland[de]GrÖnland[es]Groenlandia[it]Groenlandia[nl]Groenland[pt]Gronelândia</multi>'),
        array('id_pays'=>'80','code'=>'GP','code_num'=>312,'code_alpha3'=>'GLP','nom'=>'<multi>[fr]Guadeloupe[en]Guadeloupe[de]Guadeloupe[es]Guadalupe[it]Guadalupa[nl]Guadeloupe[pt]Guadalupe</multi>'),
        array('id_pays'=>'81','code'=>'GU','code_num'=>316,'code_alpha3'=>'GUM','nom'=>'<multi>[fr]Guam[en]Guam[de]Guam[es]Guam[it]Guam[nl]Guam[pt]Guam</multi>'),
        array('id_pays'=>'82','code'=>'GT','code_num'=>320,'code_alpha3'=>'GTM','nom'=>'<multi>[fr]Guatemala[en]Guatemala[de]Guatemala[es]Guatemala[it]Guatemala[nl]Guatemala[pt]Guatemala</multi>'),
        array('id_pays'=>'83','code'=>'GG','code_num'=>831,'code_alpha3'=>'GGY','nom'=>'<multi>[fr]Guernesey[en]Guernsey[de]Guernsey[es]Guernsey[it]Guernsey[nl]Guernsey[pt]Guernsey</multi>'),
        array('id_pays'=>'84','code'=>'GN','code_num'=>324,'code_alpha3'=>'GIN','nom'=>'<multi>[fr]Guinée[en]Guinea[de]Guinea[es]Guinea[it]Guinea[nl]Guinee[pt]Guiné</multi>'),
        array('id_pays'=>'85','code'=>'GW','code_num'=>624,'code_alpha3'=>'GNB','nom'=>'<multi>[fr]Guinée équatoriale[en]Equatorial Guinea[de]äquatorialguinea[es]Guinea Ecuatorial[it]Guinea Equatoriale[nl]Equatoriaal-Guinea[pt]Guiné Equatorial</multi>'),
        array('id_pays'=>'86','code'=>'GQ','code_num'=>226,'code_alpha3'=>'GNQ','nom'=>'<multi>[fr]Guinée-Bissau[en]Guinea-Bissau[de]Guinea-Bissau[es]Guinea-Bissau[it]Guinea-Bissau[nl]Guinee-Bissau[pt]Guiné-Bissau</multi>'),
        array('id_pays'=>'87','code'=>'GY','code_num'=>328,'code_alpha3'=>'GUY','nom'=>'<multi>[fr]Guyana[en]Guyana[de]Guyana[es]Guyana[it]Guyana[nl]Guyana[pt]Guiana</multi>'),
        array('id_pays'=>'88','code'=>'GF','code_num'=>254,'code_alpha3'=>'GUF','nom'=>'<multi>[fr]Guyane[en]Guyana[de]Guyana[es]Guyana[it]Guyana[nl]Frans-Guyana[pt]Guiana</multi>'),
        array('id_pays'=>'89','code'=>'HT','code_num'=>332,'code_alpha3'=>'HTI','nom'=>'<multi>[fr]Haïti[en]Haiti[de]Haiti[es]Haití[it]Haiti[nl]Haïti[pt]Haiti</multi>'),
        array('id_pays'=>'90','code'=>'HN','code_num'=>340,'code_alpha3'=>'HND','nom'=>'<multi>[fr]Honduras[en]Honduras[de]Honduras[es]Honduras[it]Honduras[nl]Honduras[pt]Honduras</multi>'),
        array('id_pays'=>'91','code'=>'HK','code_num'=>344,'code_alpha3'=>'HKG','nom'=>'<multi>[fr]Hong Kong[en]Hong Kong[de]Hong Kong[es]Hong Kong[it]Hong Kong[nl]Hongkong[pt]Hong Kong</multi>'),
        array('id_pays'=>'92','code'=>'HU','code_num'=>348,'code_alpha3'=>'HUN','nom'=>'<multi>[fr]Hongrie[en]Hungary[de]Ungarn[es]Hungría[it]Ungheria[nl]Hongarije[pt]Hungria</multi>'),
        array('id_pays'=>'93','code'=>'BV','code_num'=>74,'code_alpha3'=>'BVT','nom'=>'<multi>[fr]Île Bouvet[en]Bouvet Island[de]Bouvet-Insel[es]Isla Bouvet[it]Isola Bouvet[nl]Bouvet[pt]Ilha Bouvet</multi>'),
        array('id_pays'=>'94','code'=>'CX','code_num'=>162,'code_alpha3'=>'CXR','nom'=>'<multi>[fr]Île Christmas[en]Christmas Island[de]Osterinsel[es]Christmas Island[it]Isola di Natale[nl]Christmaseiland[pt]Christmas Island</multi>'),
        array('id_pays'=>'95','code'=>'IM','code_num'=>833,'code_alpha3'=>'IMN','nom'=>'<multi>[fr]Île de Man[en]Isle of Man[de]Isle of Man[es]Isla de Man[it]Isola di Man[nl]Man[pt]Isle of Man</multi>'),
        array('id_pays'=>'96','code'=>'KY','code_num'=>136,'code_alpha3'=>'CYM','nom'=>'<multi>[fr]Îles Caïmanes[en]Cayman Islands[de]Kaimaninseln[es]De las Islas Caimán[it]Isole Cayman[nl]Caymaneilanden[pt]Ilhas Cayman</multi>'), // Dédicace à Cyril
        array('id_pays'=>'97','code'=>'CC','code_num'=>166,'code_alpha3'=>'CCK','nom'=>'<multi>[fr]Îles Cocos[en]Cocos[de]Kokosinseln[es]Cocos[it]Isole Cocos[nl]Cocoseilanden[pt]Cocos</multi>'),
        array('id_pays'=>'98','code'=>'CK','code_num'=>184,'code_alpha3'=>'COK','nom'=>'<multi>[fr]Îles Cook[en]Cook Islands[de]Cook-Inseln[es]Islas Cook[it]Isole Cook[nl]Cookeilanden[pt]Ilhas Cook</multi>'),
        array('id_pays'=>'99','code'=>'FO','code_num'=>234,'code_alpha3'=>'FRO','nom'=>'<multi>[fr]Îles Féroé[en]Faroe Islands[de]FärÖer-Inseln[es]Islas Feroe[it]Isole Faroe[nl]FaerÃ¶er[pt]Ilhas Faroe</multi>'),
        array('id_pays'=>'100','code'=>'FK','code_num'=>238,'code_alpha3'=>'FLK','nom'=>'<multi>[fr]Îles Malouines (Falkland)[en]Islas Malvinas (Falkland)[de]Falklandinseln (Falkland)[es]Islas Malvinas (Falkland)[it]Islas Malvinas (Falkland)[nl]Falklandeilanden[pt]Islas Malvinas (Falkland)</multi>'),
        array('id_pays'=>'101','code'=>'MP','code_num'=>580,'code_alpha3'=>'MNP','nom'=>'<multi>[fr]Îles Mariannes du Nord[en]Northern Mariana Islands[de]NÖrdliche Marianen[es]Islas Marianas del Norte[it]Isole Marianne Settentrionali[nl]Noordelijke Marianen[pt]Ilhas Marianas do Norte</multi>'),
        array('id_pays'=>'102','code'=>'UM','code_num'=>581,'code_alpha3'=>'UMI','nom'=>'<multi>[fr]Îles mineures éloignées des États-Unis[en]Minor Outlying Islands of the United States[de]Kleinere entlegenen Inseln der USA[es]Islas menores alejadas de los Estados Unidos[it]Isole Minori degli Stati Uniti[nl]Kleine afgelegen eilanden van de Verenigde Staten[pt]Territórios Insulares dos Estados Unidos da</multi>'),
        array('id_pays'=>'103','code'=>'SB','code_num'=>90,'code_alpha3'=>'SLB','nom'=>'<multi>[fr]Îles Salomon[en]Solomon Islands[de]Salomonen[es]Islas Salomón[it]Isole Salomone[nl]Salomonseilanden[pt]Ilhas Salomão</multi>'),
        array('id_pays'=>'104','code'=>'TC','code_num'=>796,'code_alpha3'=>'TCA','nom'=>'<multi>[fr]Îles Turques et Caïques[en]Turks and Caicos Islands[de]Turks-und Caicosinseln[es]Islas Turcas y Caicos[it]Isole Turks e Caicos[nl]Turks- en Caicoseilanden[pt]Ilhas Turcas e Caicos</multi>'),
        array('id_pays'=>'105','code'=>'VI','code_num'=>850,'code_alpha3'=>'VIR','nom'=>'<multi>[fr]Îles Vierges américaines[en]United States Virgin Islands[de]Amerikanische Jungferninseln[es]Islas Vírgenes de los Estados Unidos[it]United States Virgin Islands[nl]Amerikaanse Maagdeneilanden[pt]Estados Unidos Ilhas Virgens</multi>'),
        array('id_pays'=>'106','code'=>'VG','code_num'=>92,'code_alpha3'=>'VGB','nom'=>'<multi>[fr]Îles Vierges britanniques[en]BVI[de]Britische Jungferninseln[es]Islas Vírgenes Británicas[it]BVI[nl]Britse Maagdeneilanden[pt]BVI</multi>'),
        array('id_pays'=>'107','code'=>'IN','code_num'=>356,'code_alpha3'=>'IND','nom'=>'<multi>[fr]Inde[en]India[de]Indien[es]India[it]India[nl]India[pt]índia</multi>'),
        array('id_pays'=>'108','code'=>'ID','code_num'=>360,'code_alpha3'=>'IDN','nom'=>'<multi>[fr]Indonésie[en]Indonesia[de]Indonesien[es]Indonesia[it]Indonesia[nl]Indonesië[pt]Indonésia</multi>'),
        array('id_pays'=>'109','code'=>'IQ','code_num'=>368,'code_alpha3'=>'IRQ','nom'=>'<multi>[fr]Irak[en]Iraq[de]Irak[es]Iraq[it]Iraq[nl]Irak[pt]Iraque</multi>'),
        array('id_pays'=>'110','code'=>'IR','code_num'=>364,'code_alpha3'=>'IRN','nom'=>'<multi>[fr]Iran[en]Iran[de]Iran[es]Irán[it]Iran[nl]Iran[pt]Irão</multi>'),
        array('id_pays'=>'111','code'=>'IE','code_num'=>372,'code_alpha3'=>'IRL','nom'=>'<multi>[fr]Irlande[en]Ireland[de]Irland[es]Irlanda[it]Irlanda[nl]Ierland[pt]Irlanda</multi>'),
        array('id_pays'=>'112','code'=>'IS','code_num'=>352,'code_alpha3'=>'ISL','nom'=>'<multi>[fr]Islande[en]Iceland[de]Island[es]Islandia[it]Islanda[nl]IJsland[pt]Islândia</multi>'),
        array('id_pays'=>'113','code'=>'IL','code_num'=>376,'code_alpha3'=>'ISR','nom'=>'<multi>[fr]Israël[en]Israel[de]Israel[es]Israel[it]Israele[nl]Israël[pt]Israel</multi>'),
        array('id_pays'=>'114','code'=>'IT','code_num'=>380,'code_alpha3'=>'ITA','nom'=>'<multi>[fr]Italie[en]Italy[de]Italien[es]Italia[it]Italia[nl]Italië[pt]Itália</multi>'),
        array('id_pays'=>'115','code'=>'JM','code_num'=>388,'code_alpha3'=>'JAM','nom'=>'<multi>[fr]Jamaïque[en]Jamaica[de]Jamaika[es]Jamaica[it]Giamaica[nl]Jamaica[pt]Jamaica</multi>'),
        array('id_pays'=>'116','code'=>'JP','code_num'=>392,'code_alpha3'=>'JPN','nom'=>'<multi>[fr]Japon[en]Japan[de]Japan[es]Japón[it]Giappone[nl]Japan[pt]Japão</multi>'),
        array('id_pays'=>'117','code'=>'JE','code_num'=>832,'code_alpha3'=>'JEY','nom'=>'<multi>[fr]Jersey[en]Jersey[de]Jersey[es]Jersey[it]Maglia[nl]Jersey[pt]Jersey</multi>'),
        array('id_pays'=>'118','code'=>'JO','code_num'=>400,'code_alpha3'=>'JOR','nom'=>'<multi>[fr]Jordanie[en]Jordan[de]Jordanien[es]Jordania[it]Giordania[nl]Jordanië[pt]Jordânia</multi>'),
        array('id_pays'=>'119','code'=>'KZ','code_num'=>398,'code_alpha3'=>'KAZ','nom'=>'<multi>[fr]Kazakhstan[en]Kazakhstan[de]Kasachstan[es]Kazajstán[it]Kazakistan[nl]Kazachstan[pt]Cazaquistão</multi>'),
        array('id_pays'=>'120','code'=>'KE','code_num'=>404,'code_alpha3'=>'KEN','nom'=>'<multi>[fr]Kenya[en]Kenya[de]Kenia[es]Kenia[it]Kenya[nl]Kenia[pt]Quénia</multi>'),
        array('id_pays'=>'121','code'=>'KG','code_num'=>417,'code_alpha3'=>'KGZ','nom'=>'<multi>[fr]Kirghizstan[en]Kyrgyzstan[de]Kirgisistan[es]Kirguistán[it]Kirghizistan[nl]Kirgizië[pt]Quirguistão</multi>'),
        array('id_pays'=>'122','code'=>'KI','code_num'=>296,'code_alpha3'=>'KIR','nom'=>'<multi>[fr]Kiribati[en]Kiribati[de]Kiribati[es]Kiribati[it]Kiribati[nl]Kiribati[pt]Kiribati</multi>'),
        array('id_pays'=>'123','code'=>'KW','code_num'=>414,'code_alpha3'=>'KWT','nom'=>'<multi>[fr]Koweït[en]Kuwait[de]Kuwait[es]Kuwait[it]Kuwait[nl]Koeweit[pt]Kuwait</multi>'),
        array('id_pays'=>'124','code'=>'LA','code_num'=>418,'code_alpha3'=>'LAO','nom'=>'<multi>[fr]Laos[en]Laos[de]Laos[es]Laos[it]Laos[nl]Laos[pt]Laos</multi>'),
        array('id_pays'=>'125','code'=>'LS','code_num'=>426,'code_alpha3'=>'LSO','nom'=>'<multi>[fr]Lesotho[en]Lesotho[de]Lesotho[es]Lesotho[it]Lesotho[nl]Lesotho[pt]Lesoto</multi>'),
        array('id_pays'=>'126','code'=>'LV','code_num'=>428,'code_alpha3'=>'LVA','nom'=>'<multi>[fr]Lettonie[en]Latvia[de]Lettland[es]Letonia[it]Lettonia[nl]Letland[pt]Letónia</multi>'),
        array('id_pays'=>'127','code'=>'LB','code_num'=>422,'code_alpha3'=>'LBN','nom'=>'<multi>[fr]Liban[en]Lebanon[de]Libanon[es]Líbano[it]Libano[nl]Libanon[pt]Líbano</multi>'),
        array('id_pays'=>'128','code'=>'LR','code_num'=>430,'code_alpha3'=>'LBR','nom'=>'<multi>[fr]Libéria[en]Liberia[de]Liberia[es]Liberia[it]Liberia[nl]Liberia[pt]Libéria</multi>'),
        array('id_pays'=>'129','code'=>'LY','code_num'=>434,'code_alpha3'=>'LBY','nom'=>'<multi>[fr]Libye[en]Libya[de]Libyen[es]Libia[it]Libia[nl]Libië[pt]Líbia</multi>'),
        array('id_pays'=>'130','code'=>'LI','code_num'=>438,'code_alpha3'=>'LIE','nom'=>'<multi>[fr]Liechtenstein[en]Liechtenstein[de]Liechtenstein[es]Liechtenstein[it]Liechtenstein[nl]Liechtenstein[pt]Liechtenstein</multi>'),
        array('id_pays'=>'131','code'=>'LT','code_num'=>440,'code_alpha3'=>'LTU','nom'=>'<multi>[fr]Lituanie[en]Lithuania[de]Litauen[es]Lituania[it]Lituania[nl]Litouwen[pt]Lituânia</multi>'),
        array('id_pays'=>'132','code'=>'LU','code_num'=>442,'code_alpha3'=>'LUX','nom'=>'<multi>[fr]Luxembourg[en]Luxembourg[de]Luxemburg[es]Luxemburgo[it]Lussemburgo[nl]Luxemburg[pt]Luxemburgo</multi>'),
        array('id_pays'=>'133','code'=>'MO','code_num'=>446,'code_alpha3'=>'MAC','nom'=>'<multi>[fr]Macao[en]Macao[de]Macau[es]Macao[it]Macao[nl]Macau[pt]Macau</multi>'),
        array('id_pays'=>'134','code'=>'MK','code_num'=>807,'code_alpha3'=>'MKD','nom'=>'<multi>[fr]Macédoine[en]Macedonia[de]Mazedonien[es]Macedonia[it]Macedonia[nl]Macedonië[pt]Macedónia</multi>'),
        array('id_pays'=>'135','code'=>'MG','code_num'=>450,'code_alpha3'=>'MDG','nom'=>'<multi>[fr]Madagascar[en]Madagascar[de]Madagaskar[es]Madagascar[it]Madagascar[nl]Madagaskar[pt]Madagascar</multi>'),
        array('id_pays'=>'136','code'=>'MY','code_num'=>458,'code_alpha3'=>'MYS','nom'=>'<multi>[fr]Malaisie[en]Malaysia[de]Malaysia[es]Malasia[it]Malesia[nl]Maleisië[pt]Malásia</multi>'),
        array('id_pays'=>'137','code'=>'MW','code_num'=>454,'code_alpha3'=>'MWI','nom'=>'<multi>[fr]Malawi[en]Malawi[de]Malawi[es]Malawi[it]Malawi[nl]Malawi[pt]Malawi</multi>'),
        array('id_pays'=>'138','code'=>'MV','code_num'=>462,'code_alpha3'=>'MDV','nom'=>'<multi>[fr]Maldives[en]Maldives[de]Malediven[es]Maldivas[it]Maldive[nl]Maldiven[pt]Maldivas</multi>'),
        array('id_pays'=>'139','code'=>'ML','code_num'=>466,'code_alpha3'=>'MLI','nom'=>'<multi>[fr]Mali[en]Mali[de]Mali[es]Malí[it]Mali[nl]Mali[pt]Mali</multi>'),
        array('id_pays'=>'140','code'=>'MT','code_num'=>470,'code_alpha3'=>'MLT','nom'=>'<multi>[fr]Malte[en]Malta[de]Malta[es]Malta[it]Malta[nl]Malta[pt]Malta</multi>'),
        array('id_pays'=>'141','code'=>'MA','code_num'=>504,'code_alpha3'=>'MAR','nom'=>'<multi>[fr]Maroc[en]Morocco[de]Marokko[es]Marruecos[it]Marocco[nl]Marokko[pt]Marrocos</multi>'),
        array('id_pays'=>'142','code'=>'MH','code_num'=>584,'code_alpha3'=>'MHL','nom'=>'<multi>[fr]Marshall[en]Marshall[de]Marshall[es]Marshall[it]Marshall[nl]Marshalleilanden[pt]Marshall</multi>'),
        array('id_pays'=>'143','code'=>'MQ','code_num'=>474,'code_alpha3'=>'MTQ','nom'=>'<multi>[fr]Martinique[en]Martinique[de]Martinique[es]Martinica[it]Martinica[nl]Martinique[pt]Martinica</multi>'),
        array('id_pays'=>'144','code'=>'MU','code_num'=>480,'code_alpha3'=>'MUS','nom'=>'<multi>[fr]Maurice[en]Mauritius[de]Mauritius[es]Mauricio[it]Maurizio[nl]Mauritius[pt]Maurícia</multi>'),
        array('id_pays'=>'145','code'=>'MR','code_num'=>478,'code_alpha3'=>'MRT','nom'=>'<multi>[fr]Mauritanie[en]Mauritania[de]Mauretanien[es]Mauritania[it]Mauritania[nl]Mauritanië[pt]Mauritânia</multi>'),
        array('id_pays'=>'146','code'=>'YT','code_num'=>175,'code_alpha3'=>'MYT','nom'=>'<multi>[fr]Mayotte[en]Mayotte[de]Mayotte[es]Mayotte[it]Mayotte[nl]Mayotte[pt]Mayotte</multi>'),
        array('id_pays'=>'147','code'=>'MX','code_num'=>484,'code_alpha3'=>'MEX','nom'=>'<multi>[fr]Mexique[en]Mexico[de]Mexiko[es]México[it]Messico[nl]Mexico[pt]México</multi>'),
        array('id_pays'=>'148','code'=>'FM','code_num'=>583,'code_alpha3'=>'FSM','nom'=>'<multi>[fr]Micronésie[en]Micronesia[de]Mikronesien[es]Micronesia[it]Micronesia[nl]Micronesia[pt]Micronésia</multi>'),
        array('id_pays'=>'149','code'=>'MD','code_num'=>498,'code_alpha3'=>'MDA','nom'=>'<multi>[fr]Moldavie[en]Moldova[de]Moldawien[es]Moldavia[it]Moldavia[nl]Moldavië[pt]Moldávia</multi>'),
        array('id_pays'=>'150','code'=>'MC','code_num'=>492,'code_alpha3'=>'MCO','nom'=>'<multi>[fr]Monaco[en]Monaco[de]Monaco[es]Mónaco[it]Monaco[nl]Monaco[pt]Monaco</multi>'),
        array('id_pays'=>'151','code'=>'MN','code_num'=>496,'code_alpha3'=>'MNG','nom'=>'<multi>[fr]Mongolie[en]Mongolia[de]Mongolei[es]Mongolia[it]Mongolia[nl]Mongolië[pt]Mongólia</multi>'),
        array('id_pays'=>'152','code'=>'ME','code_num'=>499,'code_alpha3'=>'MNE','nom'=>'<multi>[fr]Monténégro[en]Montenegro[de]Montenegro[es]Montenegro[it]Montenegro[nl]Montenegro[pt]Montenegro</multi>'),
        array('id_pays'=>'153','code'=>'MS','code_num'=>500,'code_alpha3'=>'MSR','nom'=>'<multi>[fr]Montserrat[en]Montserrat[de]Montserrat[es]Montserrat[it]Montserrat[nl]Montserrat[pt]Montserrat</multi>'),
        array('id_pays'=>'154','code'=>'MZ','code_num'=>508,'code_alpha3'=>'MOZ','nom'=>'<multi>[fr]Mozambique[en]Mozambique[de]Mosambik[es]Mozambique[it]Mozambico[nl]Mozambique[pt]Moçambique</multi>'),
        array('id_pays'=>'155','code'=>'NA','code_num'=>516,'code_alpha3'=>'NAM','nom'=>'<multi>[fr]Namibie[en]Namibia[de]Namibia[es]Namibia[it]Namibia[nl]Namibië[pt]Namíbia</multi>'),
        array('id_pays'=>'156','code'=>'NR','code_num'=>520,'code_alpha3'=>'NRU','nom'=>'<multi>[fr]Nauru[en]Nauru[de]Nauru[es]Nauru[it]Nauru[nl]Nauru[pt]Nauru</multi>'),
        array('id_pays'=>'157','code'=>'NP','code_num'=>524,'code_alpha3'=>'NPL','nom'=>'<multi>[fr]Népal[en]Nepal[de]Nepal[es]Nepal[it]Nepal[nl]Nepal[pt]Nepal</multi>'),
        array('id_pays'=>'158','code'=>'NI','code_num'=>558,'code_alpha3'=>'NIC','nom'=>'<multi>[fr]Nicaragua[en]Nicaragua[de]Nicaragua[es]Nicaragua[it]Nicaragua[nl]Nicaragua[pt]Nicarágua</multi>'),
        array('id_pays'=>'159','code'=>'NE','code_num'=>562,'code_alpha3'=>'NER','nom'=>'<multi>[fr]Niger[en]Niger[de]Niger[es]Níger[it]Niger[nl]Niger[pt]Níger</multi>'),
        array('id_pays'=>'160','code'=>'NG','code_num'=>566,'code_alpha3'=>'NGA','nom'=>'<multi>[fr]Nigeria[en]Nigeria[de]Nigeria[es]Nigeria[it]Nigeria[nl]Nigeria[pt]Nigéria</multi>'),
        array('id_pays'=>'161','code'=>'NU','code_num'=>570,'code_alpha3'=>'NIU','nom'=>'<multi>[fr]Niué[en]Niue[de]Niue[es]Niue[it]Niue[nl]Niue[pt]Niue</multi>'),
        array('id_pays'=>'162','code'=>'NF','code_num'=>574,'code_alpha3'=>'NFK','nom'=>'<multi>[fr]Norfolk[en]Norfolk[de]Norfolk[es]Norfolk[it]Norfolk[nl]Norfolk[pt]Norfolk</multi>'),
        array('id_pays'=>'163','code'=>'NO','code_num'=>578,'code_alpha3'=>'NOR','nom'=>'<multi>[fr]Norvège[en]Norway[de]Norwegen[es]Noruega[it]Norvegia[nl]Noorwegen[pt]Noruega</multi>'),
        array('id_pays'=>'164','code'=>'NC','code_num'=>540,'code_alpha3'=>'NCL','nom'=>'<multi>[fr]Nouvelle-Calédonie[en]New Caledonia[de]Neukaledonien[es]Nueva Caledonia[it]Nuova Caledonia[nl]Nieuw-Caledonië[pt]Nova Caledônia</multi>'),
        array('id_pays'=>'165','code'=>'NZ','code_num'=>554,'code_alpha3'=>'NZL','nom'=>'<multi>[fr]Nouvelle-Zélande[en]New Zealand[de]Neuseeland[es]Nueva Zelandia[it]Nuova Zelanda[nl]Nieuw-Zeeland[pt]Nova Zelândia</multi>'),
        array('id_pays'=>'166','code'=>'OM','code_num'=>512,'code_alpha3'=>'OMN','nom'=>'<multi>[fr]Oman[en]Oman[de]Oman[es]Omán[it]Oman[nl]Oman[pt]Omã</multi>'),
        array('id_pays'=>'167','code'=>'UG','code_num'=>800,'code_alpha3'=>'UGA','nom'=>'<multi>[fr]Ouganda[en]Uganda[de]Uganda[es]Uganda[it]Uganda[nl]Uganda[pt]Uganda</multi>'),
        array('id_pays'=>'168','code'=>'UZ','code_num'=>860,'code_alpha3'=>'UZB','nom'=>'<multi>[fr]Ouzbékistan[en]Uzbekistan[de]Usbekistan[es]Uzbekistán[it]Uzbekistan[nl]Oezbekistan[pt]Uzbequistão</multi>'),
        array('id_pays'=>'169','code'=>'PK','code_num'=>586,'code_alpha3'=>'PAK','nom'=>'<multi>[fr]Pakistan[en]Pakistan[de]Pakistan[es]Pakistán[it]Pakistan[nl]Pakistan[pt]Paquistão</multi>'),
        array('id_pays'=>'170','code'=>'PW','code_num'=>585,'code_alpha3'=>'PLW','nom'=>'<multi>[fr]Palaos[en]Palau[de]Palau[es]Palau[it]Palau[nl]Palau[pt]Palau</multi>'),
        array('id_pays'=>'171','code'=>'PS','code_num'=>275,'code_alpha3'=>'PSE','nom'=>'<multi>[fr]Palestine[en]Palestine[de]Palästina[es]Palestina[it]Palestina[nl]Palestijnse Autoriteit[pt]Palestina</multi>'),
        array('id_pays'=>'172','code'=>'PA','code_num'=>591,'code_alpha3'=>'PAN','nom'=>'<multi>[fr]Panamá[en]Panamá[de]Panama-Stadt[es]Panamá[it]Panamá[nl]Panama[pt]Panamá</multi>'),
        array('id_pays'=>'173','code'=>'PG','code_num'=>598,'code_alpha3'=>'PNG','nom'=>'<multi>[fr]Papouasie-Nouvelle-Guinée[en]Papua New Guinea[de]Papua-Neuguinea[es]Papua Nueva Guinea[it]Papua Nuova Guinea[nl]Papoea-Nieuw-Guinea[pt]Papua Nova Guiné</multi>'),
        array('id_pays'=>'174','code'=>'PY','code_num'=>600,'code_alpha3'=>'PRY','nom'=>'<multi>[fr]Paraguay[en]Paraguay[de]Paraguay[es]Paraguay[it]Paraguay[nl]Paraguay[pt]Paraguai</multi>'),
        array('id_pays'=>'175','code'=>'NL','code_num'=>528,'code_alpha3'=>'NLD','nom'=>'<multi>[fr]Pays-Bas[en]Netherlands[de]Niederlande[es]Países Bajos[it]Paesi Bassi[nl]Nederland[[pt]Holanda</multi>'),
        array('id_pays'=>'176','code'=>'PE','code_num'=>604,'code_alpha3'=>'PER','nom'=>'<multi>[fr]Pérou[en]Peru[de]Peru[es]Perú[it]Perù[nl]Peru[pt]Peru</multi>'),
        array('id_pays'=>'177','code'=>'PH','code_num'=>608,'code_alpha3'=>'PHL','nom'=>'<multi>[fr]Philippines[en]Philippines[de]Philippinen[es]Filipinas[it]Filippine[nl]Filipijnen[pt]Filipinas</multi>'),
        array('id_pays'=>'178','code'=>'PN','code_num'=>612,'code_alpha3'=>'PCN','nom'=>'<multi>[fr]Pitcairn[en]Pitcairn[de]Pitcairn[es]Pitcairn[it]Pitcairn[nl]Pitcairneilanden[pt]Pitcairn</multi>'),
        array('id_pays'=>'179','code'=>'PL','code_num'=>616,'code_alpha3'=>'POL','nom'=>'<multi>[fr]Pologne[en]Poland[de]Polen[es]Polonia[it]Polonia[nl]Polen[pt]Polônia</multi>'),
        array('id_pays'=>'180','code'=>'PF','code_num'=>258,'code_alpha3'=>'PYF','nom'=>'<multi>[fr]Polynésie française[en]French Polynesia[de]FranzÖsisch-Polynesien[es]Polinesia francés[it]Polinesia Francese[nl]Frans-Polynesië[pt]Polinésia Francesa</multi>'),
        array('id_pays'=>'181','code'=>'PR','code_num'=>630,'code_alpha3'=>'PRI','nom'=>'<multi>[fr]Porto Rico[en]Puerto Rico[de]Puerto Rico[es]Puerto Rico[it]Puerto Rico[nl]Puerto Rico[pt]Porto Rico</multi>'),
        array('id_pays'=>'182','code'=>'PT','code_num'=>620,'code_alpha3'=>'PRT','nom'=>'<multi>[fr]Portugal[en]Portugal[de]Portugal[es]Portugal[it]Portogallo[nl]Portugal[pt]Portugal</multi>'),
        array('id_pays'=>'183','code'=>'QA','code_num'=>634,'code_alpha3'=>'QAT','nom'=>'<multi>[fr]Qatar[en]Qatar[de]Katar[es]Qatar[it]Qatar[nl]Qatar[pt]Qatar</multi>'),
        array('id_pays'=>'184','code'=>'DO','code_num'=>214,'code_alpha3'=>'DOM','nom'=>'<multi>[fr]République dominicaine[en]Dominican Republic[de]Dominikanische Republik[es]República Dominicana[it]Repubblica Dominicana[nl]Dominicaanse Republiek[pt]República Dominicana</multi>'),
        array('id_pays'=>'185','code'=>'CZ','code_num'=>203,'code_alpha3'=>'CZE','nom'=>'<multi>[fr]République tchèque[en]Czech Republic[de]Tschechische Republik[es]República Checa[it]Repubblica Ceca[nl]Tsjechië[pt]República Checa</multi>'),
        array('id_pays'=>'186','code'=>'RE','code_num'=>638,'code_alpha3'=>'REU','nom'=>'<multi>[fr]Réunion[en]Reunion[de]Réunion[es]Reunión[it]Reunion[nl]Réunion[pt]Reunion</multi>'),
        array('id_pays'=>'187','code'=>'RO','code_num'=>642,'code_alpha3'=>'ROU','nom'=>'<multi>[fr]Roumanie[en]Romania[de]Rumänien[es]Rumania[it]Romania[nl]Roemenië[pt]Roménia</multi>'),
        array('id_pays'=>'188','code'=>'GB','code_num'=>826,'code_alpha3'=>'GBR','nom'=>'<multi>[fr]Royaume-Uni[en]United Kingdom[de]Gro§britannien[es]Reino Unido[it]Regno Unito[nl]Verenigd Koninkrijk[pt]Reino Unido</multi>'),
        array('id_pays'=>'189','code'=>'RU','code_num'=>643,'code_alpha3'=>'RUS','nom'=>'<multi>[fr]Russie[en]Russia[de]Russland[es]Rusia[it]Russia[nl]Rusland[pt]Rússia</multi>'),
        array('id_pays'=>'190','code'=>'RW','code_num'=>646,'code_alpha3'=>'RWA','nom'=>'<multi>[fr]Rwanda[en]Rwanda[de]Ruanda[es]Ruanda[it]Ruanda[nl]Rwanda[pt]Ruanda</multi>'),
        array('id_pays'=>'191','code'=>'EH','code_num'=>732,'code_alpha3'=>'ESH','nom'=>'<multi>[fr]Sahara occidental[en]Western Sahara[de]Westsahara[es]Sáhara Occidental[it]Sahara Occidentale[pt]Sara Ocidental</multi>'),
        array('id_pays'=>'192','code'=>'KN','code_num'=>659,'code_alpha3'=>'KNA','nom'=>'<multi>[fr]Saint-Christophe-et-Niévès[en]St. Christopher St Kitts and Nevis[de]St. Kitts und Nevis[es]St Christopher St Kitts y Nevis[it]St Christopher St Kitts e Nevis[nl]Saint Kitts en Nevis[pt]São Cristóvão St Kitts e Nevis</multi>'),
        array('id_pays'=>'193','code'=>'SH','code_num'=>654,'code_alpha3'=>'SHN','nom'=>'<multi>[fr]Sainte-Hélène[en]St. Helena[de]St. Helena[es]Santa Elena[it]St Helena[nl]Sint-Helena, Ascension en Tristan da Cunha[pt]Santa Helena</multi>'),
        array('id_pays'=>'194','code'=>'LC','code_num'=>662,'code_alpha3'=>'LCA','nom'=>'<multi>[fr]Sainte-Lucie[en]St. Lucia[de]St. Lucia[es]Santa Lucía[it]Santa Lucia[nl]Saint Lucia[pt]St. Lucia</multi>'),
        array('id_pays'=>'195','code'=>'SM','code_num'=>388,'code_alpha3'=>'JAM','nom'=>'<multi>[fr]Saint-Marin[en]San Marino[de]San Marino[es]San Marino[it]San Marino[nl]San Marino[pt]San Marino</multi>'),
        array('id_pays'=>'196','code'=>'PM','code_num'=>666,'code_alpha3'=>'SPM','nom'=>'<multi>[fr]Saint-Pierre-et-Miquelon[en]Saint-Pierre and Miquelon[de]Saint-Pierre und Miquelon[es]Saint-Pierre y Miquelón[it]Saint-Pierre e Miquelon[nl]Saint-Pierre en Miquelon[pt]Saint-Pierre e Miquelon</multi>'),
        array('id_pays'=>'197','code'=>'VC','code_num'=>670,'code_alpha3'=>'VCT','nom'=>'<multi>[fr]Saint-Vincent-et-les Grenadines[en]Saint Vincent and the Grenadines[de]St. Vincent und die Grenadinen[es]San Vicente y las Granadinas[it]Saint Vincent e Grenadine[nl]Saint Vincent en de Grenadines[pt]São Vicente e Granadinas</multi>'),
        array('id_pays'=>'198','code'=>'SV','code_num'=>222,'code_alpha3'=>'SLV','nom'=>'<multi>[fr]Salvador[en]Salvador[de]Salvador[es]Salvador[it]Salvador[nl]El Salvador[pt]Salvador</multi>'),
        array('id_pays'=>'199','code'=>'WS','code_num'=>882,'code_alpha3'=>'WSM','nom'=>'<multi>[fr]Samoa[en]Samoa[de]Samoa[es]Samoa[it]Samoa[nl]Samoa[pt]Samoa</multi>'),
        array('id_pays'=>'200','code'=>'AS','code_num'=>'016','code_alpha3'=>'ASM','nom'=>'<multi>[fr]Samoa américaines[en]American Samoa[de]Amerikanisch-Samoa[es]Samoa Americana[it]Samoa Americane[nl]Amerikaans-Samoa[pt]Samoa Americana</multi>'),
        array('id_pays'=>'201','code'=>'ST','code_num'=>678,'code_alpha3'=>'STP','nom'=>'<multi>[fr]São Tomé-et-Principe[en]Sao Tome and Principe[de]São Tomé und Principe[es]Santo Tomé y Príncipe[it]Sao Tome e Principe[pt]São Tomé e Príncipe[nl]Sao Tomé en Principe</multi>'),
        array('id_pays'=>'202','code'=>'SN','code_num'=>686,'code_alpha3'=>'SEN','nom'=>'<multi>[fr]Sénégal[en]Senegal[de]Senegal[es]Senegal[it]Senegal[nl]Senegal[pt]Senegal</multi>'),
        array('id_pays'=>'203','code'=>'RS','code_num'=>688,'code_alpha3'=>'SRB','nom'=>'<multi>[fr]Serbie[en]Serbia[de]Serbien[es]Serbia[it]Serbia[nl]Servië[pt]Sérvia</multi>'),
        array('id_pays'=>'204','code'=>'SC','code_num'=>690,'code_alpha3'=>'SYC','nom'=>'<multi>[fr]Seychelles[en]Seychelles[de]Seychellen[es]Seychelles[it]Seychelles[nl]Seychellen[pt]Seychelles</multi>'),
        array('id_pays'=>'205','code'=>'SL','code_num'=>694,'code_alpha3'=>'SLE','nom'=>'<multi>[fr]Sierra Leone[en]Sierra Leone[de]Sierra Leone[es]Sierra Leona[it]Sierra Leone[nl]Sierra Leone[pt]Serra Leoa</multi>'),
        array('id_pays'=>'206','code'=>'SG','code_num'=>702,'code_alpha3'=>'SGP','nom'=>'<multi>[fr]Singapour[en]Singapore[de]Singapur[es]Singapur[it]Singapore[nl]Singapore[pt]Singapura</multi>'),
        array('id_pays'=>'207','code'=>'SK','code_num'=>703,'code_alpha3'=>'SVK','nom'=>'<multi>[fr]Slovaquie[en]Slovakia[de]Slowakei[es]Eslovaquia[it]Slovacchia[nl]Slowakije[pt]Eslováquia</multi>'),
        array('id_pays'=>'208','code'=>'SI','code_num'=>705,'code_alpha3'=>'SVN','nom'=>'<multi>[fr]Slovénie[en]Slovenia[de]Slowenien[es]Eslovenia[it]Slovenia[nl]Slovenië[pt]Eslovénia</multi>'), // je l'aime bien celui là : SVN
        array('id_pays'=>'209','code'=>'SO','code_num'=>706,'code_alpha3'=>'SOM','nom'=>'<multi>[fr]Somalie[en]Somalia[de]Somalia[es]Somalia[it]Somalia[nl]Somalië[pt]Somália</multi>'),
        array('id_pays'=>'210','code'=>'SD','code_num'=>729,'code_alpha3'=>'SDN','nom'=>'<multi>[fr]Soudan[en]Sudan[de]Sudan[es]Sudán[it]Sudan[nl]Soedan[pt]Sudão</multi>'),
        array('id_pays'=>'211','code'=>'LK','code_num'=>144,'code_alpha3'=>'LKA','nom'=>'<multi>[fr]Sri Lanka[en]Sri Lanka[de]Sri Lanka[es]Sri Lanka[it]Sri Lanka[nl]Sri Lanka[pt]Sri Lanka</multi>'),
        array('id_pays'=>'212','code'=>'SE','code_num'=>752,'code_alpha3'=>'SWE','nom'=>'<multi>[fr]Suède[en]Sweden[de]Schweden[es]Suecia[it]Svezia[nl]Zweden[pt]Suécia</multi>'),
        array('id_pays'=>'213','code'=>'CH','code_num'=>756,'code_alpha3'=>'CHE','nom'=>'<multi>[fr]Suisse[en]Switzerland[de]Schweiz[es]Suiza[it]Svizzera[nl]Zwitserland[pt]Suíça</multi>'),
        array('id_pays'=>'214','code'=>'SR','code_num'=>740,'code_alpha3'=>'SUR','nom'=>'<multi>[fr]Suriname[en]Suriname[de]Suriname[es]Surinam[it]Suriname[nl]Suriname[pt]Suriname</multi>'),
        array('id_pays'=>'215','code'=>'SJ','code_num'=>744,'code_alpha3'=>'SJM','nom'=>'<multi>[fr]Svalbard et île Jan Mayen[en]Svalbard and Jan Mayen Island[de]Svalbard und Jan Mayen Insel[es]Svalbard y Jan Mayen Island[it]Svalbard e Jan Mayen, isola[nl]Jan Mayen[pt]Svalbard e Jan Mayen Island</multi>'),
        array('id_pays'=>'216','code'=>'SZ','code_num'=>748,'code_alpha3'=>'SWZ','nom'=>'<multi>[fr]Swaziland[en]Swaziland[de]Swasiland[es]Swazilandia[it]Swaziland[nl]Swaziland[pt]Suazilândia</multi>'),
        array('id_pays'=>'217','code'=>'SY','code_num'=>760,'code_alpha3'=>'SYR','nom'=>'<multi>[fr]Syrie[en]Syria[de]Syrien[es]Siria[it]Siria[nl]Syrië[pt]Síria</multi>'),
        array('id_pays'=>'218','code'=>'TJ','code_num'=>762,'code_alpha3'=>'TJK','nom'=>'<multi>[fr]Tadjikistan[en]Tajikistan[de]Tadschikistan[es]Tayikistán[it]Tagikistan[nl]Tadzjikistan[pt]Tajiquistão</multi>'),
        array('id_pays'=>'219','code'=>'TW','code_num'=>158,'code_alpha3'=>'TWN','nom'=>'<multi>[fr]Taïwan[en]Taiwan[de]Taiwan[es]Taiwán[it]Taiwan[nl]Taiwan[pt]Taiwan</multi>'),
        array('id_pays'=>'220','code'=>'TZ','code_num'=>834,'code_alpha3'=>'TZA','nom'=>'<multi>[fr]Tanzanie[en]Tanzania[de]Tansania[es]Tanzania[it]Tanzania[nl]Tanzania[pt]Tanzânia</multi>'),
        array('id_pays'=>'221','code'=>'TD','code_num'=>148,'code_alpha3'=>'TCD','nom'=>'<multi>[fr]Tchad[en]Chad[de]Tschad[es]Chad[it]Ciad[nl]Tsjaad[pt]Chade</multi>'),
        array('id_pays'=>'222','code'=>'TF','code_num'=>260,'code_alpha3'=>'ATF','nom'=>'<multi>[fr]Terres australes et antarctiques françaises[en]French Southern and Antarctic Territories[de]Wallis und Futuna[es]Francés australes y antárticas[it]Terre australi e antartiche francesi[nl]Franse Zuidelijke en Antarctische Gebieden[pt]Territórios Austrais e Antárcticos Franceses</multi>'),
        array('id_pays'=>'223','code'=>'IO','code_num'=>'086','code_alpha3'=>'IOT','nom'=>'<multi>[fr]Territoire britannique de l\'océan Indien[en]British Indian Ocean[de]Britisches Territorium im Indischen Ozean[es]Británico del Océano índico[it]Britannici dell\'Oceano Indiano[pt]Britânico do Oceano índico[nl]Brits Territorium in de Indische Oceaan</multi>'),
        array('id_pays'=>'224','code'=>'__','code_num'=>'000','code_alpha3'=>'___','nom'=>'<multi>[fr]Territoires extérieurs de l\'Australie[en]External territories of Australia[de]Gebiete au§erhalb von Australien[es]Territorios externos de Australia[it]Territori esterni di Australia[pt]External territórios da Austrália</multi>'),
        array('id_pays'=>'225','code'=>'TH','code_num'=>795,'code_alpha3'=>'TKM','nom'=>'<multi>[fr]Thaïlande[en]Thailand[de]Thailand[es]Tailandia[it]Thailandia[nl]Thailand[pt]Tailândia</multi>'),
        array('id_pays'=>'226','code'=>'TL','code_num'=>626,'code_alpha3'=>'TLS','nom'=>'<multi>[fr]Timor oriental[en]East Timor[de]Osttimor[es]Timor Oriental[it]Timor Est[nl]Oost-Timor[pt]Timor-Leste</multi>'),
        array('id_pays'=>'227','code'=>'TG','code_num'=>768,'code_alpha3'=>'TGO','nom'=>'<multi>[fr]Togo[en]Togo[de]Togo[es]Togo[it]Togo[nl]Togo[pt]Togo</multi>'),
        array('id_pays'=>'228','code'=>'TK','code_num'=>772,'code_alpha3'=>'TKL','nom'=>'<multi>[fr]Tokelau[en]Tokelau[de]Tokelau[es]Tokelau[it]Tokelau[nl]Tokelau-eilanden[pt]Tokelau</multi>'),
        array('id_pays'=>'229','code'=>'TO','code_num'=>776,'code_alpha3'=>'TON','nom'=>'<multi>[fr]Tonga[en]Tonga[de]Tonga[es]Tonga[it]Tonga[nl]Tonga[pt]Tonga</multi>'),
        array('id_pays'=>'230','code'=>'TT','code_num'=>780,'code_alpha3'=>'TTO','nom'=>'<multi>[fr]Trinité-et-Tobago[en]Trinidad and Tobago[de]Trinidad und Tobago[es]Trinidad y Tobago[it]Trinidad e Tobago[nl]Trinidad en Tobago[pt]Trinidad e Tobago</multi>'),
        array('id_pays'=>'231','code'=>'TN','code_num'=>788,'code_alpha3'=>'TUN','nom'=>'<multi>[fr]Tunisie[en]Tunisia[de]Tunesien[es]Túnez[it]Tunisia[nl]Tunesië[pt]Tunísia</multi>'),
        array('id_pays'=>'232','code'=>'TM','code_num'=>795,'code_alpha3'=>'TKM','nom'=>'<multi>[fr]Turkménistan[en]Turkmenistan[de]Turkmenistan[es]Turkmenistán[it]Turkmenistan[nl]Turkmenistan[pt]Turquemenistão</multi>'),
        array('id_pays'=>'233','code'=>'TR','code_num'=>792,'code_alpha3'=>'TUR','nom'=>'<multi>[fr]Turquie[en]Turkey[de]Türkei[es]Turquía[it]Turchia[nl]Turkije[pt]Turquia</multi>'),
        array('id_pays'=>'234','code'=>'TV','code_num'=>798,'code_alpha3'=>'TUV','nom'=>'<multi>[fr]Tuvalu[en]Tuvalu[de]Tuvalu[es]Tuvalu[it]Tuvalu[nl]Tuvalu[pt]Tuvalu</multi>'),
        array('id_pays'=>'235','code'=>'UA','code_num'=>804,'code_alpha3'=>'UKR','nom'=>'<multi>[fr]Ukraine[en]Ukraine[de]Ukraine[es]Ucrania[it]Ucraina[nl]Oekraïne[[pt]Ucrânia</multi>'),
        array('id_pays'=>'236','code'=>'UY','code_num'=>858,'code_alpha3'=>'URY','nom'=>'<multi>[fr]Uruguay[en]Uruguay[de]Uruguay[es]Uruguay[it]Uruguay[nl]Uruguay[pt]Uruguai</multi>'),
        array('id_pays'=>'237','code'=>'VU','code_num'=>548,'code_alpha3'=>'VUT','nom'=>'<multi>[fr]Vanuatu[en]Vanuatu[de]Vanuatu[es]Vanuatu[it]Vanuatu[nl]Vanuatu[pt]Vanuatu</multi>'),
        array('id_pays'=>'238','code'=>'VA','code_num'=>336,'code_alpha3'=>'VAT','nom'=>'<multi>[fr]Vatican[en]Vatican[de]Vatikan[es]Vaticano[it]Vaticano[nl]Vaticaanstad[pt]Vaticano</multi>'),
        array('id_pays'=>'239','code'=>'VE','code_num'=>862,'code_alpha3'=>'VEN','nom'=>'<multi>[fr]Vénézuela[en]Venezuela[de]Venezuela[es]Venezuela[it]Venezuela[nl]Venezuela[pt]Venezuela</multi>'),
        array('id_pays'=>'240','code'=>'VN','code_num'=>704,'code_alpha3'=>'VNM','nom'=>'<multi>[fr]Viêt Nam[en]Vietnam[de]Vietnam[es]Vietnam[it]Vietnam[nl]Vietnam[pt]Vietnã</multi>'),
        array('id_pays'=>'241','code'=>'WF','code_num'=>876,'code_alpha3'=>'WLF','nom'=>'<multi>[fr]Wallis-et-Futuna[en]Wallis and Futuna[de]Wallis und Futuna[es]Wallis y Futuna[it]Wallis e Futuna[nl]Wallis en Futuna[pt]Wallis e Futuna</multi>'),
        array('id_pays'=>'242','code'=>'YE','code_num'=>887,'code_alpha3'=>'YEM','nom'=>'<multi>[fr]Yémen[en]Yemen[de]Jemen[es]Yemen[it]Yemen[nl]Jemen[pt]Iémen</multi>'),
        array('id_pays'=>'243','code'=>'ZM','code_num'=>894,'code_alpha3'=>'ZMB','nom'=>'<multi>[fr]Zambie[en]Zambia[de]Sambia[es]Zambia[it]Zambia[nl]Zambia[pt]Zâmbia</multi>'),
        array('id_pays'=>'244','code'=>'ZW','code_num'=>716,'code_alpha3'=>'ZWE','nom'=>'<multi>[fr]Zimbabwe[en]Zimbabwe[de]Simbabwe[es]Zimbabwe[it]Zimbabwe[nl]Zimbabwe[pt]Zimbabwe</multi>'),
        array('id_pays'=>'245','code'=>'BL','code_num'=>652,'code_alpha3'=>'BLM','nom'=>'<multi>[fr]Saint-Barthélemy[en]Saint-Barthélemy[de]Saint-Barthélemy[es]Saint-Barthélemy[it]Saint-Barthélemy[nl]Saint-Barthelemy[pt]Saint-Barthélemy</multi>'),
        array('id_pays'=>'246','code'=>'BQ','code_num'=>535,'code_alpha3'=>'BES','nom'=>'<multi>[fr]Pays-Bas caribéens[en]Netherlands Caribbean[de]Niederlande Karibik[es]Holanda del Caribe[it]Netherlands Caribbean[nl]Caribisch Nederland[pt]Holanda Caribe</multi>'),
        array('id_pays'=>'247','code'=>'CW','code_num'=>531,'code_alpha3'=>'CUW','nom'=>'<multi>[fr]Curaçao[en]Curacao[de]Curacao[es]Curacao[it]Curacao[nl]Curacao[pt]Curaçao</multi>'),
        array('id_pays'=>'248','code'=>'HM','code_num'=>334,'code_alpha3'=>'HMD','nom'=>'<multi>[fr]Îles Heard-et-McDonald[en]Heard and McDonald Islands[de]Heard und McDonaldinseln[es]Islas Heard y McDonald[it]Isole Heard e McDonald[nl]Heard- en McDonaldeilanden[pt]Ilhas Heard e McDonald</multi>'),
        array('id_pays'=>'249','code'=>'SS','code_num'=>728,'code_alpha3'=>'SSD','nom'=>'<multi>[fr]Soudan du Sud[en]South Sudan[de]Süd-Sudan[es]Sudán del Sur[it]Sud Sudan[nl]Zuid-Soedan[pt]Sudão do Sul</multi>'),
        array('id_pays'=>'250','code'=>'SX','code_num'=>534,'code_alpha3'=>'SXM','nom'=>'<multi>[fr]Sint Maarten[en]Sint Maarten[de]Sint Maarten[es]Sint Maarten[it]Sint Maarten[nl]Sint Maarten[pt]Sint Maarten</multi>'),
            )
    );
}
?>
