<?php
#La liste de pays sera recopiee sur la table spip_geo_pays en ordre alphabetique
$GLOBALS['liste_pays'] = array(

// A
1=>"<multi>[fr]Afghanistan[en]Afghanistan[de]Afghanistan[es]Afganist&aacute;n[it]Afghanistan[nl]Afghanistan[pt]Afeganist&atilde;o</multi>",
2=>"<multi>[fr]Afrique du Sud[en]South Africa[de]S&uuml;d-Afrika[es]Sud&aacute;frica[it]Sud Africa[nl]Zuid-Afrika[pt]&aacute;frica do Sul</multi>",
3=>"<multi>[fr]&Aring;land[en]&Aring;land[de]&Aring;land[es]&Aring;land[it]&Aring;land[nl]&Aring;land[pt]&Aring;land</multi>",
4=>"<multi>[fr]Albanie[en]Albania[de]Albanien[es]Albania[it]Albania[nl]Albani&euml;[pt]Alb&acirc;nia</multi>",
5=>"<multi>[fr]Alg&eacute;rie[en]Algeria[de]Algerien[es]Argelia[it]Algeria[nl]Algerije[pt]Arg&eacute;lia</multi>",
6=>"<multi>[fr]Allemagne[en]Germany[de]Deutschland[es]Alemania[it]Germania[nl]Duitsland[pt]Alemanha</multi>",
7=>"<multi>[fr]Andorre[en]Andorra[de]Andorra[es]Andorra[it]Andorra[nl]Andorra[pt]Andorra</multi>",
8=>"<multi>[fr]Angola[en]Angola[de]Angola[es]Angola[it]Angola[nl]Angola[pt]Angola</multi>",
9=>"<multi>[fr]Anguilla[en]Anguilla[de]Anguilla[es]Anguila[it]Anguilla[nl]Anguilla[pt]Anguilla</multi>",
10=>"<multi>[fr]Antarctique[en]Antarctica[de]Antarktis[es]Ant&aacute;rtida[it]Antartide[pt]Ant&aacute;rtica</multi>",
11=>"<multi>[fr]Antigua-et-Barbuda[en]Antigua and Barbuda[de]Antigua und Barbuda[es]Antigua y Barbuda[it]Antigua e Barbuda[nl]Antigua en Barbuda[pt]Antigua e Barbuda</multi>",
12=>"<multi>[fr]Antilles n&eacute;erlandaises[en]Netherlands Antilles[de]Niederl&auml;ndische Antillen[es]Antillas Neerlandesas[it]Antille olandesi[nl]Nederlandse Antillen[pt]Antilhas Holandesas</multi>",
13=>"<multi>[fr]Arabie saoudite[en]Saudi Arabia[de]Saudi-Arabien[es]Arabia Saudita[it]Arabia Saudita[nl]Saoedi-Arabi&euml;[pt]Ar&aacute;bia Saudita</multi>",
14=>"<multi>[fr]Argentine[en]Argentina[de]Argentinien[es]Argentina[it]Argentina[nl]Argentini&euml;[pt]Argentina</multi>",
15=>"<multi>[fr]Arm&eacute;nie[en]Armenia[de]Armenien[es]Armenia[it]Armenia[nl]Armeni&euml;[pt]Arm&eacute;nia</multi>",
16=>"<multi>[fr]Aruba[en]Aruba[de]Aruba[es]Aruba[it]Aruba[nl]Aruba[pt]Aruba</multi>",
17=>"<multi>[fr]Australie[en]Australia[de]Australien[es]Australia[it]Australia[nl]Australi&euml;[pt]Austr&aacute;lia</multi>",
18=>"<multi>[fr]Autriche[en]Austria[de]&Ouml;sterreich[es]Austria[it]Austria[nl]Oostenrijk[pt]&aacute;ustria</multi>",
19=>"<multi>[fr]Azerba&iuml;djan[en]Azerbaijan[de]Aserbaidschan[es]Azerbaiy&aacute;n[it]Azerbaigian[nl]Azerbeidzjan[pt]Azerbaij&atilde;o</multi>",

// B
20=>"<multi>[fr]Bahamas[en]Bahamas[de]Bahamas[es]Bahamas[it]Bahamas[nl]Bahama's[pt]Bahamas</multi>",
21=>"<multi>[fr]Bahre&iuml;n[en]Bahrain[de]Bahrain[es]Bahrein[it]Bahrein[nl]Bahrein[pt]Bahrein</multi>",
22=>"<multi>[fr]Bangladesh[en]Bangladesh[de]Bangladesch[es]Bangladesh[it]Bangladesh[nl]Bangladesh[pt]Bangladesh</multi>",
23=>"<multi>[fr]Barbade[en]Barbados[de]Barbados[es]Barbados[it]Barbados[nl]Barbados[pt]Barbados</multi>",
24=>"<multi>[fr]Belgique[en]Belgium[de]Belgien[es]B&eacute;lgica[it]Belgio[nl]Belgi&euml;[pt]B&eacute;lgica</multi>",
25=>"<multi>[fr]Belize[en]Belize[de]Belize[es]Belice[it]Belize[nl]Belize[pt]Belize</multi>",
26=>"<multi>[fr]B&eacute;nin[en]Benin[de]Benin[es]Benin[it]Benin[nl]Benin[pt]Benin</multi>",
27=>"<multi>[fr]Bermudes[en]Bermuda[de]Bermuda[es]Bermudas[it]Bermuda[nl]Bermuda[pt]Bermudas</multi>",
28=>"<multi>[fr]Bhoutan[en]Bhutan[de]Bhutan[es]But&aacute;n[it]Bhutan[nl]Bhutan[pt]But&atilde;o</multi>",
29=>"<multi>[fr]Bi&eacute;lorussie[en]Belarus[de]Wei&#167;russland[es]Bielorrusia[it]Bielorussia[nl]Wit-Rusland[pt]Belarus</multi>",
30=>"<multi>[fr]Birmanie[en]Burma[de]Birma[es]Birmania[it]Birmania[nl]Myanmar[pt]Birm&acirc;nia</multi>",
31=>"<multi>[fr]Bolivie[en]Bolivia[de]Bolivien[es]Bolivia[it]Bolivia[nl]Bolivia[pt]Bol&iacute;via</multi>",
32=>"<multi>[fr]Bosnie-Herz&eacute;govine[en]Bosnia and Herzegovina[de]Bosnien-Herzegowina[es]Bosnia y Herzegovina[it]Bosnia-Erzegovina[nl]Bosni&euml; en Herzegovina[pt]B&oacute;snia e Herzegovina</multi>",
33=>"<multi>[fr]Botswana[en]Botswana[de]Botswana[es]Botswana[it]Botswana[nl]Botswana[pt]Botsuana</multi>",
34=>"<multi>[fr]Br&eacute;sil[en]Brazil[de]Brasilien[es]Brasil[it]Brasile[nl]Brazili&euml;[pt]Brasil</multi>",
35=>"<multi>[fr]Brunei[en]Brunei[de]Brunei[es]Brunei[it]Brunei[nl]Brunei[pt]Brunei</multi>",
36=>"<multi>[fr]Bulgarie[en]Bulgaria[de]Bulgarien[es]Bulgaria[it]Bulgaria[nl]Bulgarije[pt]Bulg&aacute;ria</multi>",
37=>"<multi>[fr]Burkina Faso[en]Burkina Faso[de]Burkina Faso[es]Burkina Faso[it]Burkina Faso[nl]Burkina Faso[pt]Burkina Faso</multi>",
38=>"<multi>[fr]Burundi[en]Burundi[de]Burundi[es]Burundi[it]Burundi[nl]Burundi[pt]Burundi</multi>",

// C
39=>"<multi>[fr]Cambodge[en]Cambodia[de]Kambodscha[es]Camboya[it]Cambogia[nl]Cambodja[pt]Camboja</multi>",
40=>"<multi>[fr]Cameroun[en]Cameroon[de]Kamerun[es]Camer&uacute;n[it]Camerun[nl]Kameroen[pt]Camar&otilde;es</multi>",
41=>"<multi>[fr]Canada[en]Canada[de]Kanada[es]Canad&aacute;[it]Canada[nl]Canada[pt]Canad&aacute;</multi>",
42=>"<multi>[fr]Cap-Vert[en]Cape Verde[de]Kap Verde[es]Cabo Verde[it]Capo Verde[nl]Kaapverdi&euml;[pt]Cabo Verde</multi>",
43=>"<multi>[fr]Centrafrique[en]Central African Republic[de]Zentralafrika[es]Rep. Centroafricana[it]Repubblica Centrafricana[nl]Centraal-Afrikaanse Republiek[pt]Rep&ugrave;blica Centro-Africana</multi>",
44=>"<multi>[fr]Chili[en]Chile[de]Chile[es]Chile[it]Cile[nl]Chili[pt]Chile</multi>",
45=>"<multi>[fr]Chine[en]China[de]China[es]China[it]Cina[nl]China[pt]China</multi>",
46=>"<multi>[fr]Chypre[en]Cyprus[de]Zypern[es]Chipre[it]Cipro[nl]Cyprus[pt]Chipre</multi>",
47=>"<multi>[fr]Colombie[en]Colombia[de]Kolumbien[es]Colombia[it]Colombia[nl]Colombia[pt]Col&ocirc;mbia</multi>",
48=>"<multi>[fr]Comores[en]Comoros[de]Komoren[es]Comoras[it]Comore[nl]Comoren[pt]Comores</multi>",
49=>"<multi>[fr]Congo-Brazzaville[en]Congo-Brazzaville[de]Kongo-Brazzaville[es]Congo-Brazzaville[it]Congo-Brazzaville[nl]Congo-Brazzaville[pt]Congo-Brazzaville</multi>",
50=>"<multi>[fr]Congo-Kinshasa[en]Congo-Kinshasa[de]Kongo-Kinshasa[es]Congo-Kinshasa[it]Congo-Kinshasa[nl]Congo-Kinshasa[pt]Congo-Kinshasa</multi>",
51=>"<multi>[fr]Cor&eacute;e du Nord[en]North Korea[de]Nordkorea[es]Corea del Norte[it]Corea del Nord[nl]Noord-Korea[pt]Coreia do Norte</multi>",
52=>"<multi>[fr]Cor&eacute;e du Sud[en]South Korea[de]S&uuml;dkorea[es]Corea del Sur[it]Corea del Sud[nl]Zuid-Korea[pt]Cor&eacute;ia do Sul</multi>",
53=>"<multi>[fr]Costa Rica[en]Costa Rica[de]Costa Rica[es]Costa Rica[it]Costa Rica[nl]Costa Rica[pt]Costa Rica</multi>",
54=>"<multi>[fr]C&ocirc;te d'Ivoire[en]C&ocirc;te d'Ivoire[de]C&ocirc;te d'Ivoire[es]C&ocirc;te d'Ivoire[it]Costa d'Avorio[nl]Ivoorkust[pt]Costa do Marfim</multi>",
55=>"<multi>[fr]Croatie[en]Croatia[de]Kroatien[es]Croacia[it]Croazia[nl]Kroati&euml;[pt]Cro&aacute;cia</multi>",
56=>"<multi>[fr]Cuba[en]Cuba[de]Kuba[es]Cuba[it]Cuba[nl]Cuba[pt]Cuba</multi>",

// D
57=>"<multi>[fr]Danemark[en]Denmark[de]D&auml;nemark[es]Dinamarca[it]Danimarca[nl]Denemarken[pt]Dinamarca</multi>",
58=>"<multi>[fr]Djibouti[en]Djibouti[de]Dschibuti[es]Djibouti[it]Gibuti[nl]Djibouti[pt]Djibouti</multi>",
59=>"<multi>[fr]Dominique[en]Dominica[de]Dominica[es]Dominica[it]Dominica[nl]Dominica[pt]Dominica</multi>",

// E
60=>"<multi>[fr]&Eacute;gypte[en]Egypt[de]&auml;gypten[es]Egipto[it]Egitto[nl]Egypte[pt]Egito</multi>",
61=>"<multi>[fr]&Eacute;mirats arabes unis[en]United Arab Emirates[de]Vereinigte Arabische Emirate[es]Emiratos &aacute;rabes Unidos[it]Emirati Arabi Uniti[nl]Verenigde Arabische Emiraten[pt]Emirados &aacute;rabes Unidos</multi>",
62=>"<multi>[fr]&Eacute;quateur[en]Ecuador[de]Ecuador[es]Ecuador[it]Ecuador[nl]Ecuador[pt]Equador</multi>",
63=>"<multi>[fr]&Eacute;rythr&eacute;e[en]Eritrea[de]Eritrea[es]Eritrea[it]Eritrea[nl]Eritrea[pt]Eritreia</multi>",
64=>"<multi>[fr]Espagne[en]Spain[de]Spanien[es]Espa&ntilde;a[it]Spagna[nl]Spanje[pt]Espanha</multi>",
65=>"<multi>[fr]Estonie[en]Estonia[de]Estland[es]Estonia[it]Estonia[nl]Estland[pt]Est&oacute;nia</multi>",
66=>"<multi>[fr]&Eacute;tats-Unis[en]United States[de]Vereinigte Staaten[es]Estados Unidos[it]Stati Uniti[nl]Verenigde Staten[pt]Estados Unidos</multi>",
67=>"<multi>[fr]&Eacute;thiopie[en]Ethiopia[de]&auml;thiopien[es]Etiop&iacute;a[it]Etiopia[nl]Ethiopi&euml;[pt]Eti&oacute;pia</multi>",

// F
68=>"<multi>[fr]Fidji[en]Fiji[de]Fidschi[es]Fiji[it]Figi[nl]Fiji[pt]Fiji</multi>",
69=>"<multi>[fr]Finlande[en]Finland[de]Finnland[es]Finlandia[it]Finlandia[nl]Finland[pt]Finl&acirc;ndia</multi>",
70=>"<multi>[fr]France[en]France[de]Frankreich[es]Francia[it]Francia[nl]Frankrijk[pt]Fran&ccedil;a</multi>",

// G
71=>"<multi>[fr]Gabon[en]Gabon[de]Gabun[es]Gab&oacute;n[it]Gabon[nl]Gabon[pt]Gab&atilde;o</multi>",
72=>"<multi>[fr]Gambie[en]Gambia[de]Gambia[es]Gambia[it]Gambia[nl]Gambia[pt]G&acirc;mbia</multi>",
73=>"<multi>[fr]G&eacute;orgie[en]Georgia[de]Georgien[es]Georgia[it]Georgia[nl]Georgi&euml;[pt]Ge&oacute;rgia</multi>",
74=>"<multi>[fr]G&eacute;orgie du Sud et les &icirc;les Sandwich du Sud[en]South Georgia and the South Sandwich Islands[de]S&uuml;d-Georgien und die S&uuml;d-Sandwich-Inseln[es]Georgia del Sur y las Islas Sandwich del Sur[it]Georgia del Sud e il Sud e Isole Sandwich[nl]Zuid-Georgi&euml; en de Zuidelijke Sandwicheilanden[pt]Ge&oacute;rgia do Sul e Sandwich do Sul Ilhas</multi>",
75=>"<multi>[fr]Ghana[en]Ghana[de]Ghana[es]Ghana[it]Ghana[nl]Ghana[pt]Gana</multi>",
76=>"<multi>[fr]Gibraltar[en]Gibraltar[de]Gibraltar[es]Gibraltar[it]Gibilterra[nl]Gibraltar[pt]Gibraltar</multi>",
77=>"<multi>[fr]Gr&egrave;ce[en]Greece[de]Griechenland[es]Grecia[it]Grecia[nl]Griekenland[pt]Gr&eacute;cia</multi>",
78=>"<multi>[fr]Grenade[en]Grenada[de]Granada[es]Granada[it]Grenada[nl]Grenada[pt]Grenada</multi>",
79=>"<multi>[fr]Groenland[en]Greenland[de]Gr&Ouml;nland[es]Groenlandia[it]Groenlandia[nl]Groenland[pt]Gronel&acirc;ndia</multi>",
80=>"<multi>[fr]Guadeloupe[en]Guadeloupe[de]Guadeloupe[es]Guadalupe[it]Guadalupa[nl]Guadeloupe[pt]Guadalupe</multi>",
81=>"<multi>[fr]Guam[en]Guam[de]Guam[es]Guam[it]Guam[nl]Guam[pt]Guam</multi>",
82=>"<multi>[fr]Guatemala[en]Guatemala[de]Guatemala[es]Guatemala[it]Guatemala[nl]Guatemala[pt]Guatemala</multi>",
83=>"<multi>[fr]Guernesey[en]Guernsey[de]Guernsey[es]Guernsey[it]Guernsey[nl]Guernsey[pt]Guernsey</multi>",
84=>"<multi>[fr]Guin&eacute;e[en]Guinea[de]Guinea[es]Guinea[it]Guinea[nl]Guinee[pt]Guin&eacute;</multi>",
85=>"<multi>[fr]Guin&eacute;e &eacute;quatoriale[en]Equatorial Guinea[de]&auml;quatorialguinea[es]Guinea Ecuatorial[it]Guinea Equatoriale[nl]Equatoriaal-Guinea[pt]Guin&eacute; Equatorial</multi>",
86=>"<multi>[fr]Guin&eacute;e-Bissau[en]Guinea-Bissau[de]Guinea-Bissau[es]Guinea-Bissau[it]Guinea-Bissau[nl]Guinee-Bissau[pt]Guin&eacute;-Bissau</multi>",
87=>"<multi>[fr]Guyana[en]Guyana[de]Guyana[es]Guyana[it]Guyana[nl]Guyana[pt]Guiana</multi>",
88=>"<multi>[fr]Guyane[en]Guyana[de]Guyana[es]Guyana[it]Guyana[nl]Frans-Guyana[pt]Guiana</multi>",

// H
89=>"<multi>[fr]Ha&iuml;ti[en]Haiti[de]Haiti[es]Hait&iacute;[it]Haiti[nl]Ha&iuml;ti[pt]Haiti</multi>",
90=>"<multi>[fr]Honduras[en]Honduras[de]Honduras[es]Honduras[it]Honduras[nl]Honduras[pt]Honduras</multi>",
91=>"<multi>[fr]Hong Kong[en]Hong Kong[de]Hong Kong[es]Hong Kong[it]Hong Kong[nl]Hongkong[pt]Hong Kong</multi>",
92=>"<multi>[fr]Hongrie[en]Hungary[de]Ungarn[es]Hungr&iacute;a[it]Ungheria[nl]Hongarije[pt]Hungria</multi>",

// I
93=>"<multi>[fr]&Icirc;le Bouvet[en]Bouvet Island[de]Bouvet-Insel[es]Isla Bouvet[it]Isola Bouvet[nl]Bouvet[pt]Ilha Bouvet</multi>",
94=>"<multi>[fr]&Icirc;le Christmas[en]Christmas Island[de]Osterinsel[es]Christmas Island[it]Isola di Natale[nl]Christmaseiland[pt]Christmas Island</multi>",
95=>"<multi>[fr]&Icirc;le de Man[en]Isle of Man[de]Isle of Man[es]Isla de Man[it]Isola di Man[nl]Man[pt]Isle of Man</multi>",
96=>"<multi>[fr]&Icirc;les Ca&iuml;manes[en]Cayman Islands[de]Kaimaninseln[es]De las Islas Caim&aacute;n[it]Isole Cayman[nl]Caymaneilanden[pt]Ilhas Cayman</multi>",
97=>"<multi>[fr]&Icirc;les Cocos[en]Cocos[de]Kokosinseln[es]Cocos[it]Isole Cocos[nl]Cocoseilanden[pt]Cocos</multi>",
98=>"<multi>[fr]&Icirc;les Cook[en]Cook Islands[de]Cook-Inseln[es]Islas Cook[it]Isole Cook[nl]Cookeilanden[pt]Ilhas Cook</multi>",
99=>"<multi>[fr]&Icirc;les F&eacute;ro&eacute;[en]Faroe Islands[de]F&auml;r&Ouml;er-Inseln[es]Islas Feroe[it]Isole Faroe[nl]FaerÃ¶er[pt]Ilhas Faroe</multi>",
100=>"<multi>[fr]&Icirc;les Malouines (Falkland)[en]Islas Malvinas (Falkland)[de]Falklandinseln (Falkland)[es]Islas Malvinas (Falkland)[it]Islas Malvinas (Falkland)[nl]Falklandeilanden[pt]Islas Malvinas (Falkland)</multi>",
101=>"<multi>[fr]&Icirc;les Mariannes du Nord[en]Northern Mariana Islands[de]N&Ouml;rdliche Marianen[es]Islas Marianas del Norte[it]Isole Marianne Settentrionali[nl]Noordelijke Marianen[pt]Ilhas Marianas do Norte</multi>",
102=>"<multi>[fr]&Icirc;les mineures &eacute;loign&eacute;es des &Eacute;tats-Unis[en]Minor Outlying Islands of the United States[de]Kleinere entlegenen Inseln der USA[es]Islas menores alejadas de los Estados Unidos[it]Isole Minori degli Stati Uniti[nl]Kleine afgelegen eilanden van de Verenigde Staten[pt]Territ&oacute;rios Insulares dos Estados Unidos da</multi>",
103=>"<multi>[fr]&Icirc;les Salomon[en]Solomon Islands[de]Salomonen[es]Islas Salom&oacute;n[it]Isole Salomone[nl]Salomonseilanden[pt]Ilhas Salom&atilde;o</multi>",
104=>"<multi>[fr]&Icirc;les Turques et Ca&iuml;ques[en]Turks and Caicos Islands[de]Turks-und Caicosinseln[es]Islas Turcas y Caicos[it]Isole Turks e Caicos[nl]Turks- en Caicoseilanden[pt]Ilhas Turcas e Caicos</multi>",
105=>"<multi>[fr]&Icirc;les Vierges am&eacute;ricaines[en]United States Virgin Islands[de]Amerikanische Jungferninseln[es]Islas V&iacute;rgenes de los Estados Unidos[it]United States Virgin Islands[nl]Amerikaanse Maagdeneilanden[pt]Estados Unidos Ilhas Virgens</multi>",
106=>"<multi>[fr]&Icirc;les Vierges britanniques[en]BVI[de]Britische Jungferninseln[es]Islas V&iacute;rgenes Brit&aacute;nicas[it]BVI[nl]Britse Maagdeneilanden[pt]BVI</multi>",
107=>"<multi>[fr]Inde[en]India[de]Indien[es]India[it]India[nl]India[pt]&iacute;ndia</multi>",
108=>"<multi>[fr]Indon&eacute;sie[en]Indonesia[de]Indonesien[es]Indonesia[it]Indonesia[nl]Indonesi&euml;[pt]Indon&eacute;sia</multi>",
109=>"<multi>[fr]Irak[en]Iraq[de]Irak[es]Iraq[it]Iraq[nl]Irak[pt]Iraque</multi>",
110=>"<multi>[fr]Iran[en]Iran[de]Iran[es]Ir&aacute;n[it]Iran[nl]Iran[pt]Ir&atilde;o</multi>",
111=>"<multi>[fr]Irlande[en]Ireland[de]Irland[es]Irlanda[it]Irlanda[nl]Ierland[pt]Irlanda</multi>",
112=>"<multi>[fr]Islande[en]Iceland[de]Island[es]Islandia[it]Islanda[nl]IJsland[pt]Isl&acirc;ndia</multi>",
113=>"<multi>[fr]Isra&euml;l[en]Israel[de]Israel[es]Israel[it]Israele[nl]Isra&euml;l[pt]Israel</multi>",
114=>"<multi>[fr]Italie[en]Italy[de]Italien[es]Italia[it]Italia[nl]Itali&euml;[pt]It&aacute;lia</multi>",

// J
115=>"<multi>[fr]Jama&iuml;que[en]Jamaica[de]Jamaika[es]Jamaica[it]Giamaica[nl]Jamaica[pt]Jamaica</multi>",
116=>"<multi>[fr]Japon[en]Japan[de]Japan[es]Jap&oacute;n[it]Giappone[nl]Japan[pt]Jap&atilde;o</multi>",
117=>"<multi>[fr]Jersey[en]Jersey[de]Jersey[es]Jersey[it]Maglia[nl]Jersey[pt]Jersey</multi>",
118=>"<multi>[fr]Jordanie[en]Jordan[de]Jordanien[es]Jordania[it]Giordania[nl]Jordani&euml;[pt]Jord&acirc;nia</multi>",

// K
119=>"<multi>[fr]Kazakhstan[en]Kazakhstan[de]Kasachstan[es]Kazajst&aacute;n[it]Kazakistan[nl]Kazachstan[pt]Cazaquist&atilde;o</multi>",
120=>"<multi>[fr]Kenya[en]Kenya[de]Kenia[es]Kenia[it]Kenya[nl]Kenia[pt]Qu&eacute;nia</multi>",
121=>"<multi>[fr]Kirghizstan[en]Kyrgyzstan[de]Kirgisistan[es]Kirguist&aacute;n[it]Kirghizistan[nl]Kirgizi&euml;[pt]Quirguist&atilde;o</multi>",
122=>"<multi>[fr]Kiribati[en]Kiribati[de]Kiribati[es]Kiribati[it]Kiribati[nl]Kiribati[pt]Kiribati</multi>",
123=>"<multi>[fr]Kowe&iuml;t[en]Kuwait[de]Kuwait[es]Kuwait[it]Kuwait[nl]Koeweit[pt]Kuwait</multi>",

// L
124=>"<multi>[fr]Laos[en]Laos[de]Laos[es]Laos[it]Laos[nl]Laos[pt]Laos</multi>",
125=>"<multi>[fr]Lesotho[en]Lesotho[de]Lesotho[es]Lesotho[it]Lesotho[nl]Lesotho[pt]Lesoto</multi>",
126=>"<multi>[fr]Lettonie[en]Latvia[de]Lettland[es]Letonia[it]Lettonia[nl]Letland[pt]Let&oacute;nia</multi>",
127=>"<multi>[fr]Liban[en]Lebanon[de]Libanon[es]L&iacute;bano[it]Libano[nl]Libanon[pt]L&iacute;bano</multi>",
128=>"<multi>[fr]Lib&eacute;ria[en]Liberia[de]Liberia[es]Liberia[it]Liberia[nl]Liberia[pt]Lib&eacute;ria</multi>",
129=>"<multi>[fr]Libye[en]Libya[de]Libyen[es]Libia[it]Libia[nl]Libi&euml;[pt]L&iacute;bia</multi>",
130=>"<multi>[fr]Liechtenstein[en]Liechtenstein[de]Liechtenstein[es]Liechtenstein[it]Liechtenstein[nl]Liechtenstein[pt]Liechtenstein</multi>",
131=>"<multi>[fr]Lituanie[en]Lithuania[de]Litauen[es]Lituania[it]Lituania[nl]Litouwen[pt]Litu&acirc;nia</multi>",
132=>"<multi>[fr]Luxembourg[en]Luxembourg[de]Luxemburg[es]Luxemburgo[it]Lussemburgo[nl]Luxemburg[pt]Luxemburgo</multi>",

// M
133=>"<multi>[fr]Macao[en]Macao[de]Macau[es]Macao[it]Macao[nl]Macau[pt]Macau</multi>",
134=>"<multi>[fr]Mac&eacute;doine[en]Macedonia[de]Mazedonien[es]Macedonia[it]Macedonia[nl]Macedoni&euml;[pt]Maced&oacute;nia</multi>",
135=>"<multi>[fr]Madagascar[en]Madagascar[de]Madagaskar[es]Madagascar[it]Madagascar[nl]Madagaskar[pt]Madagascar</multi>",
136=>"<multi>[fr]Malaisie[en]Malaysia[de]Malaysia[es]Malasia[it]Malesia[nl]Maleisi&euml;[pt]Mal&aacute;sia</multi>",
137=>"<multi>[fr]Malawi[en]Malawi[de]Malawi[es]Malawi[it]Malawi[nl]Malawi[pt]Malawi</multi>",
138=>"<multi>[fr]Maldives[en]Maldives[de]Malediven[es]Maldivas[it]Maldive[nl]Maldiven[pt]Maldivas</multi>",
139=>"<multi>[fr]Mali[en]Mali[de]Mali[es]Mal&iacute;[it]Mali[nl]Mali[pt]Mali</multi>",
140=>"<multi>[fr]Malte[en]Malta[de]Malta[es]Malta[it]Malta[nl]Malta[pt]Malta</multi>",
141=>"<multi>[fr]Maroc[en]Morocco[de]Marokko[es]Marruecos[it]Marocco[nl]Marokko[pt]Marrocos</multi>",
142=>"<multi>[fr]Marshall[en]Marshall[de]Marshall[es]Marshall[it]Marshall[nl]Marshalleilanden[pt]Marshall</multi>",
143=>"<multi>[fr]Martinique[en]Martinique[de]Martinique[es]Martinica[it]Martinica[nl]Martinique[pt]Martinica</multi>",
144=>"<multi>[fr]Maurice[en]Mauritius[de]Mauritius[es]Mauricio[it]Maurizio[nl]Mauritius[pt]Maur&iacute;cia</multi>",
145=>"<multi>[fr]Mauritanie[en]Mauritania[de]Mauretanien[es]Mauritania[it]Mauritania[nl]Mauritani&euml;[pt]Maurit&acirc;nia</multi>",
146=>"<multi>[fr]Mayotte[en]Mayotte[de]Mayotte[es]Mayotte[it]Mayotte[nl]Mayotte[pt]Mayotte</multi>",
147=>"<multi>[fr]Mexique[en]Mexico[de]Mexiko[es]Mexico[it]Messico[nl]Mexico[pt]M&eacute;xico</multi>",
148=>"<multi>[fr]Micron&eacute;sie[en]Micronesia[de]Mikronesien[es]Micronesia[it]Micronesia[nl]Micronesia[pt]Micron&eacute;sia</multi>",
149=>"<multi>[fr]Moldavie[en]Moldova[de]Moldawien[es]Moldavia[it]Moldavia[nl]Moldavi&euml;[pt]Mold&aacute;via</multi>",
150=>"<multi>[fr]Monaco[en]Monaco[de]Monaco[es]M&oacute;naco[it]Monaco[nl]Monaco[pt]Monaco</multi>",
151=>"<multi>[fr]Mongolie[en]Mongolia[de]Mongolei[es]Mongolia[it]Mongolia[nl]Mongoli&euml;[pt]Mong&oacute;lia</multi>",
152=>"<multi>[fr]Mont&eacute;n&eacute;gro[en]Montenegro[de]Montenegro[es]Montenegro[it]Montenegro[nl]Montenegro[pt]Montenegro</multi>",
153=>"<multi>[fr]Montserrat[en]Montserrat[de]Montserrat[es]Montserrat[it]Montserrat[nl]Montserrat[pt]Montserrat</multi>",
154=>"<multi>[fr]Mozambique[en]Mozambique[de]Mosambik[es]Mozambique[it]Mozambico[nl]Mozambique[pt]Mo&ccedil;ambique</multi>",

// N
155=>"<multi>[fr]Namibie[en]Namibia[de]Namibia[es]Namibia[it]Namibia[nl]Namibi&euml;[pt]Nam&iacute;bia</multi>",
156=>"<multi>[fr]Nauru[en]Nauru[de]Nauru[es]Nauru[it]Nauru[nl]Nauru[pt]Nauru</multi>",
157=>"<multi>[fr]N&eacute;pal[en]Nepal[de]Nepal[es]Nepal[it]Nepal[nl]Nepal[pt]Nepal</multi>",
158=>"<multi>[fr]Nicaragua[en]Nicaragua[de]Nicaragua[es]Nicaragua[it]Nicaragua[nl]Nicaragua[pt]Nicar&aacute;gua</multi>",
159=>"<multi>[fr]Niger[en]Niger[de]Niger[es]N&iacute;ger[it]Niger[nl]Niger[pt]N&iacute;ger</multi>",
160=>"<multi>[fr]Nigeria[en]Nigeria[de]Nigeria[es]Nigeria[it]Nigeria[nl]Nigeria[pt]Nig&eacute;ria</multi>",
161=>"<multi>[fr]Niu&eacute;[en]Niue[de]Niue[es]Niue[it]Niue[nl]Niue[pt]Niue</multi>",
162=>"<multi>[fr]Norfolk[en]Norfolk[de]Norfolk[es]Norfolk[it]Norfolk[nl]Norfolk[pt]Norfolk</multi>",
163=>"<multi>[fr]Norv&egrave;ge[en]Norway[de]Norwegen[es]Noruega[it]Norvegia[nl]Noorwegen[pt]Noruega</multi>",
164=>"<multi>[fr]Nouvelle-Cal&eacute;donie[en]New Caledonia[de]Neukaledonien[es]Nueva Caledonia[it]Nuova Caledonia[nl]Nieuw-Caledoni&euml;[pt]Nova Caled&ocirc;nia</multi>",
165=>"<multi>[fr]Nouvelle-Z&eacute;lande[en]New Zealand[de]Neuseeland[es]Nueva Zelandia[it]Nuova Zelanda[nl]Nieuw-Zeeland[pt]Nova Zel&acirc;ndia</multi>",

// O
166=>"<multi>[fr]Oman[en]Oman[de]Oman[es]Om&aacute;n[it]Oman[nl]Oman[pt]Om&atilde;</multi>",
167=>"<multi>[fr]Ouganda[en]Uganda[de]Uganda[es]Uganda[it]Uganda[nl]Uganda[pt]Uganda</multi>",
168=>"<multi>[fr]Ouzb&eacute;kistan[en]Uzbekistan[de]Usbekistan[es]Uzbekist&aacute;n[it]Uzbekistan[nl]Oezbekistan[pt]Uzbequist&atilde;o</multi>",

// P
169=>"<multi>[fr]Pakistan[en]Pakistan[de]Pakistan[es]Pakist&aacute;n[it]Pakistan[nl]Pakistan[pt]Paquist&atilde;o</multi>",
170=>"<multi>[fr]Palaos[en]Palau[de]Palau[es]Palau[it]Palau[nl]Palau[pt]Palau</multi>",
171=>"<multi>[fr]Palestine[en]Palestine[de]Pal&auml;stina[es]Palestina[it]Palestina[nl]Palestijnse Autoriteit[pt]Palestina</multi>",
172=>"<multi>[fr]Panam&aacute;[en]Panam&aacute;[de]Panama-Stadt[es]Panam&aacute;[it]Panam&aacute;[nl]Panama[pt]Panam&aacute;</multi>",
173=>"<multi>[fr]Papouasie-Nouvelle-Guin&eacute;e[en]Papua New Guinea[de]Papua-Neuguinea[es]Papua Nueva Guinea[it]Papua Nuova Guinea[nl]Papoea-Nieuw-Guinea[pt]Papua Nova Guin&eacute;</multi>",
174=>"<multi>[fr]Paraguay[en]Paraguay[de]Paraguay[es]Paraguay[it]Paraguay[nl]Paraguay[pt]Paraguai</multi>",
175=>"<multi>[fr]Pays-Bas[en]Netherlands[de]Niederlande[es]Pa&iacute;ses Bajos[it]Paesi Bassi[nl]Nederland[[pt]Holanda</multi>",
176=>"<multi>[fr]P&eacute;rou[en]Peru[de]Peru[es]Per&uacute;[it]Per&ugrave;[nl]Peru[pt]Peru</multi>",
177=>"<multi>[fr]Philippines[en]Philippines[de]Philippinen[es]Filipinas[it]Filippine[nl]Filipijnen[pt]Filipinas</multi>",
178=>"<multi>[fr]Pitcairn[en]Pitcairn[de]Pitcairn[es]Pitcairn[it]Pitcairn[nl]Pitcairneilanden[pt]Pitcairn</multi>",
179=>"<multi>[fr]Pologne[en]Poland[de]Polen[es]Polonia[it]Polonia[nl]Polen[pt]Pol&ocirc;nia</multi>",
180=>"<multi>[fr]Polyn&eacute;sie fran&ccedil;aise[en]French Polynesia[de]Franz&Ouml;sisch-Polynesien[es]Polinesia franc&eacute;s[it]Polinesia Francese[nl]Frans-Polynesi&euml;[pt]Polin&eacute;sia Francesa</multi>",
181=>"<multi>[fr]Porto Rico[en]Puerto Rico[de]Puerto Rico[es]Puerto Rico[it]Puerto Rico[nl]Puerto Rico[pt]Porto Rico</multi>",
182=>"<multi>[fr]Portugal[en]Portugal[de]Portugal[es]Portugal[it]Portogallo[nl]Portugal[pt]Portugal</multi>",

// Q
183=>"<multi>[fr]Qatar[en]Qatar[de]Katar[es]Qatar[it]Qatar[nl]Qatar[pt]Qatar</multi>",

// R
184=>"<multi>[fr]R&eacute;publique dominicaine[en]Dominican Republic[de]Dominikanische Republik[es]Rep&uacute;blica Dominicana[it]Repubblica Dominicana[nl]Dominicaanse Republiek[pt]Rep&uacute;blica Dominicana</multi>",
185=>"<multi>[fr]R&eacute;publique tch&egrave;que[en]Czech Republic[de]Tschechische Republik[es]Rep&uacute;blica Checa[it]Repubblica Ceca[nl]Tsjechi&euml;[pt]Rep&uacute;blica Checa</multi>",
186=>"<multi>[fr]R&eacute;union[en]Reunion[de]R&eacute;union[es]Reuni&oacute;n[it]Reunion[nl]R&eacute;union[pt]Reunion</multi>",
187=>"<multi>[fr]Roumanie[en]Romania[de]Rum&auml;nien[es]Rumania[it]Romania[nl]Roemeni&euml;[pt]Rom&eacute;nia</multi>",
188=>"<multi>[fr]Royaume-Uni[en]United Kingdom[de]Gro&#167;britannien[es]Reino Unido[it]Regno Unito[nl]Verenigd Koninkrijk[pt]Reino Unido</multi>",
189=>"<multi>[fr]Russie[en]Russia[de]Russland[es]Rusia[it]Russia[nl]Rusland[pt]R&uacute;ssia</multi>",
190=>"<multi>[fr]Rwanda[en]Rwanda[de]Ruanda[es]Ruanda[it]Ruanda[nl]Rwanda[pt]Ruanda</multi>",

// S
191=>"<multi>[fr]Sahara occidental[en]Western Sahara[de]Westsahara[es]S&aacute;hara Occidental[it]Sahara Occidentale[pt]Sara Ocidental</multi>",
192=>"<multi>[fr]Saint-Christophe-et-Ni&eacute;v&egrave;s[en]St. Christopher St Kitts and Nevis[de]St. Kitts und Nevis[es]St Christopher St Kitts y Nevis[it]St Christopher St Kitts e Nevis[nl]Saint Kitts en Nevis[pt]S&atilde;o Crist&oacute;v&atilde;o St Kitts e Nevis</multi>",
193=>"<multi>[fr]Sainte-H&eacute;l&egrave;ne[en]St. Helena[de]St. Helena[es]Santa Elena[it]St Helena[nl]Sint-Helena, Ascension en Tristan da Cunha[pt]Santa Helena</multi>",
194=>"<multi>[fr]Sainte-Lucie[en]St. Lucia[de]St. Lucia[es]Santa Luc&iacute;a[it]Santa Lucia[nl]Saint Lucia[pt]St. Lucia</multi>",
195=>"<multi>[fr]Saint-Marin[en]San Marino[de]San Marino[es]San Marino[it]San Marino[nl]San Marino[pt]San Marino</multi>",
196=>"<multi>[fr]Saint-Pierre-et-Miquelon[en]Saint-Pierre and Miquelon[de]Saint-Pierre und Miquelon[es]Saint-Pierre y Miquel&oacute;n[it]Saint-Pierre e Miquelon[nl]Saint-Pierre en Miquelon[pt]Saint-Pierre e Miquelon</multi>",
197=>"<multi>[fr]Saint-Vincent-et-les Grenadines[en]Saint Vincent and the Grenadines[de]St. Vincent und die Grenadinen[es]San Vicente y las Granadinas[it]Saint Vincent e Grenadine[nl]Saint Vincent en de Grenadines[pt]S&atilde;o Vicente e Granadinas</multi>",
198=>"<multi>[fr]Salvador[en]Salvador[de]Salvador[es]Salvador[it]Salvador[nl]El Salvador[pt]Salvador</multi>",
199=>"<multi>[fr]Samoa[en]Samoa[de]Samoa[es]Samoa[it]Samoa[nl]Samoa[pt]Samoa</multi>",
200=>"<multi>[fr]Samoa am&eacute;ricaines[en]American Samoa[de]Amerikanisch-Samoa[es]Samoa Americana[it]Samoa Americane[nl]Amerikaans-Samoa[pt]Samoa Americana</multi>",
201=>"<multi>[fr]S&atilde;o Tom&eacute;-et-Principe[en]Sao Tome and Principe[de]S&atilde;o Tom&eacute; und Principe[es]Santo Tom&eacute; y Pr&iacute;ncipe[it]Sao Tome e Principe[pt]S&atilde;o Tom&eacute; e Pr&iacute;ncipe[nl]Sao Tom&eacute; en Principe</multi>",
202=>"<multi>[fr]S&eacute;n&eacute;gal[en]Senegal[de]Senegal[es]Senegal[it]Senegal[nl]Senegal[pt]Senegal</multi>",
203=>"<multi>[fr]Serbie[en]Serbia[de]Serbien[es]Serbia[it]Serbia[nl]Servi&euml;[pt]S&eacute;rvia</multi>",
204=>"<multi>[fr]Seychelles[en]Seychelles[de]Seychellen[es]Seychelles[it]Seychelles[nl]Seychellen[pt]Seychelles</multi>",
205=>"<multi>[fr]Sierra Leone[en]Sierra Leone[de]Sierra Leone[es]Sierra Leona[it]Sierra Leone[nl]Sierra Leone[pt]Serra Leoa</multi>",
206=>"<multi>[fr]Singapour[en]Singapore[de]Singapur[es]Singapur[it]Singapore[nl]Singapore[pt]Singapura</multi>",
207=>"<multi>[fr]Slovaquie[en]Slovakia[de]Slowakei[es]Eslovaquia[it]Slovacchia[nl]Slowakije[pt]Eslov&aacute;quia</multi>",
208=>"<multi>[fr]Slov&eacute;nie[en]Slovenia[de]Slowenien[es]Eslovenia[it]Slovenia[nl]Sloveni&euml;[pt]Eslov&eacute;nia</multi>",
209=>"<multi>[fr]Somalie[en]Somalia[de]Somalia[es]Somalia[it]Somalia[nl]Somali&euml;[pt]Som&aacute;lia</multi>",
210=>"<multi>[fr]Soudan[en]Sudan[de]Sudan[es]Sud&aacute;n[it]Sudan[nl]Soedan[pt]Sud&atilde;o</multi>",
211=>"<multi>[fr]Sri Lanka[en]Sri Lanka[de]Sri Lanka[es]Sri Lanka[it]Sri Lanka[nl]Sri Lanka[pt]Sri Lanka</multi>",
212=>"<multi>[fr]Su&egrave;de[en]Sweden[de]Schweden[es]Suecia[it]Svezia[nl]Zweden[pt]Su&eacute;cia</multi>",
213=>"<multi>[fr]Suisse[en]Switzerland[de]Schweiz[es]Suiza[it]Svizzera[nl]Zwitserland[pt]Su&iacute;&ccedil;a</multi>",
214=>"<multi>[fr]Suriname[en]Suriname[de]Suriname[es]Surinam[it]Suriname[nl]Suriname[pt]Suriname</multi>",
215=>"<multi>[fr]Svalbard et &icirc;le Jan Mayen[en]Svalbard and Jan Mayen Island[de]Svalbard und Jan Mayen Insel[es]Svalbard y Jan Mayen Island[it]Svalbard e Jan Mayen, isola[nl]Jan Mayen[pt]Svalbard e Jan Mayen Island</multi>",
216=>"<multi>[fr]Swaziland[en]Swaziland[de]Swasiland[es]Swazilandia[it]Swaziland[nl]Swaziland[pt]Suazil&acirc;ndia</multi>",
217=>"<multi>[fr]Syrie[en]Syria[de]Syrien[es]Siria[it]Siria[nl]Syri&euml;[pt]S&iacute;ria</multi>",

// T
218=>"<multi>[fr]Tadjikistan[en]Tajikistan[de]Tadschikistan[es]Tayikist&aacute;n[it]Tagikistan[nl]Tadzjikistan[pt]Tajiquist&atilde;o</multi>",
219=>"<multi>[fr]Ta&iuml;wan[en]Taiwan[de]Taiwan[es]Taiw&aacute;n[it]Taiwan[nl]Taiwan[pt]Taiwan</multi>",
220=>"<multi>[fr]Tanzanie[en]Tanzania[de]Tansania[es]Tanzania[it]Tanzania[nl]Tanzania[pt]Tanz&acirc;nia</multi>",
221=>"<multi>[fr]Tchad[en]Chad[de]Tschad[es]Chad[it]Ciad[nl]Tsjaad[pt]Chade</multi>",
222=>"<multi>[fr]Terres australes et antarctiques fran&ccedil;aises[en]French Southern and Antarctic Territories[de]Wallis und Futuna[es]Franc&eacute;s australes y ant&aacute;rticas[it]Terre australi e antartiche francesi[nl]Franse Zuidelijke en Antarctische Gebieden[pt]Territ&oacute;rios Austrais e Ant&aacute;rcticos Franceses</multi>",
223=>"<multi>[fr]Territoire britannique de l'oc&eacute;an Indien[en]British Indian Ocean[de]Britisches Territorium im Indischen Ozean[es]Brit&aacute;nico del Oc&eacute;ano &iacute;ndico[it]Britannici dell'Oceano Indiano[pt]Brit&acirc;nico do Oceano &iacute;ndico[nl]Brits Territorium in de Indische Oceaan</multi>",
224=>"<multi>[fr]Territoires ext&eacute;rieurs de l'Australie[en]External territories of Australia[de]Gebiete au&#167;erhalb von Australien[es]Territorios externos de Australia[it]Territori esterni di Australia[pt]External territ&oacute;rios da Austr&aacute;lia</multi>",
225=>"<multi>[fr]Tha&iuml;lande[en]Thailand[de]Thailand[es]Tailandia[it]Thailandia[nl]Thailand[pt]Tail&acirc;ndia</multi>",
226=>"<multi>[fr]Timor oriental[en]East Timor[de]Osttimor[es]Timor Oriental[it]Timor Est[nl]Oost-Timor[pt]Timor-Leste</multi>",
227=>"<multi>[fr]Togo[en]Togo[de]Togo[es]Togo[it]Togo[nl]Togo[pt]Togo</multi>",
228=>"<multi>[fr]Tokelau[en]Tokelau[de]Tokelau[es]Tokelau[it]Tokelau[nl]Tokelau-eilanden[pt]Tokelau</multi>",
229=>"<multi>[fr]Tonga[en]Tonga[de]Tonga[es]Tonga[it]Tonga[nl]Tonga[pt]Tonga</multi>",
230=>"<multi>[fr]Trinit&eacute;-et-Tobago[en]Trinidad and Tobago[de]Trinidad und Tobago[es]Trinidad y Tobago[it]Trinidad e Tobago[nl]Trinidad en Tobago[pt]Trinidad e Tobago</multi>",
231=>"<multi>[fr]Tunisie[en]Tunisia[de]Tunesien[es]T&uacute;nez[it]Tunisia[nl]Tunesi&euml;[pt]Tun&iacute;sia</multi>",
232=>"<multi>[fr]Turkm&eacute;nistan[en]Turkmenistan[de]Turkmenistan[es]Turkmenist&aacute;n[it]Turkmenistan[nl]Turkmenistan[pt]Turquemenist&atilde;o</multi>",
233=>"<multi>[fr]Turquie[en]Turkey[de]T&uuml;rkei[es]Turqu&iacute;a[it]Turchia[nl]Turkije[pt]Turquia</multi>",
234=>"<multi>[fr]Tuvalu[en]Tuvalu[de]Tuvalu[es]Tuvalu[it]Tuvalu[nl]Tuvalu[pt]Tuvalu</multi>",

// U
235=>"<multi>[fr]Ukraine[en]Ukraine[de]Ukraine[es]Ucrania[it]Ucraina[nl]Oekra&iuml;ne[[pt]Ucr&acirc;nia</multi>",
236=>"<multi>[fr]Uruguay[en]Uruguay[de]Uruguay[es]Uruguay[it]Uruguay[nl]Uruguay[pt]Uruguai</multi>",

// V
237=>"<multi>[fr]Vanuatu[en]Vanuatu[de]Vanuatu[es]Vanuatu[it]Vanuatu[nl]Vanuatu[pt]Vanuatu</multi>",
238=>"<multi>[fr]Vatican[en]Vatican[de]Vatikan[es]Vaticano[it]Vaticano[nl]Vaticaanstad[pt]Vaticano</multi>",
239=>"<multi>[fr]V&eacute;n&eacute;zuela[en]Venezuela[de]Venezuela[es]Venezuela[it]Venezuela[nl]Venezuela[pt]Venezuela</multi>",
240=>"<multi>[fr]Vi&ecirc;t Nam[en]Vietnam[de]Vietnam[es]Vietnam[it]Vietnam[nl]Vietnam[pt]Vietn&atilde;</multi>",
241=>"<multi>[fr]Wallis-et-Futuna[en]Wallis and Futuna[de]Wallis und Futuna[es]Wallis y Futuna[it]Wallis e Futuna[nl]Wallis en Futuna[pt]Wallis e Futuna</multi>",

// Y
242=>"<multi>[fr]Y&eacute;men[en]Yemen[de]Jemen[es]Yemen[it]Yemen[nl]Jemen[pt]I&eacute;men</multi>",

// Z
243=>"<multi>[fr]Zambie[en]Zambia[de]Sambia[es]Zambia[it]Zambia[nl]Zambia[pt]Z&acirc;mbia</multi>",
244=>"<multi>[fr]Zimbabwe[en]Zimbabwe[de]Simbabwe[es]Zimbabwe[it]Zimbabwe[nl]Zimbabwe[pt]Zimbabwe</multi>"
);
?>