<?php

//ce fichier doit contentir plusieur tableaux 
global $tableau_traduction;
global $tableau_separateur;
global $tableau_livres;
global $livre_gateways;
$livre_gateways = array(
		'en'=>array(
			'Gn'=>1,			'1Chr'=>13,			'1Cor'=>53,			'1Jn'=>69,			'1Mc'=>20,			'1Pt'=>67,			'1Kgs'=>11,			'1Sm'=>9,			'1Thes'=>59,			'2Tm'=>61,			'1Chr'=>14,			'2Cor'=>54,			'2Jn'=>70,			'2Mac'=>21,			'2Pt'=>68,			'2Kgs'=>12,			'2Sm'=>10,			'2Thes'=>60,			'2Tm'=>62,			'3Jn'=>71,			'Hb'=>42,			'Ob'=>38,			'Hg'=>44,			'Am'=>37,			'Ap'=>73,			'Act'=>51,			'Bar'=>32,			'Sg'=>26,			'Col'=>58,			'Dn'=>34,			'Dt'=>5,			'Heb'=>65,			'Eccl'=>25,			'Eph'=>56,			'Esd'=>15,			'Est'=>19,			'Ex'=>2,			'Ez'=>33,			'Phlm'=>64,			'Phil'=>57,			'Ga'=>55,			'Jer'=>30,			'Jas'=>66,			'Jb'=>22,			'Jl'=>36,			'Jon'=>39,			'Jn'=>50,			'Jude'=>72,			'Jdt'=>18,			'Is'=>29,			'Jgs'=>7,			'Jo'=>6,			'Lam'=>31,			'Lk'=>49,			'Lv'=>3,			'Mal'=>46,			'Mk'=>48,			'Mt'=>47,			'Mi'=>40,			'Na'=>41,			'Neh'=>16,			'Nm'=>4,			'Hos'=>35,			'Prv'=>24,			'Rom'=>52,			'Ru'=>8,			'Ps'=>23,			'Ws'=>27,			'Sir'=>28,			'Zep'=>43,			'Ti'=>63,			'Tb'=>17,			'Ze'=>45));



$tableau_livres = array(
	'fr'=> array('Gn'=>'Gen&egrave;se',
	'Ex'=>'Exode',
	'Lv'=>'L&eacute;vitique',
	'Nb'=>'Nombres',
	'Dt'=>'Deut&eacute;ronome',
	'Jos'=>'Josu&eacute;',
	'Jg'=>'Juges',
	'1S'=>'1 Samuel',
	'2S'=>'2 Samuel',
	'1R'=>'1 Rois',
	'2R'=>'2 Rois',
	'1Ch'=>'1 Chroniques',
	'2Ch'=>'2 Chroniques',
	'Esd'=>'Esdras',
	'Ne'=>'N&eacute;h&eacute;mie',
	'1M'=>'1 Maccab&eacute;es',
	'2M'=>'2 Maccab&eacute;es',
	'Is'=>'Isa&iuml;e',
	'Es'=>'Esa&iuml;e',
	'Jr'=>'J&eacute;r&eacute;mie',
	'Ez'=>'Ez&eacute;quiel',
	'Os'=>'Os&eacute;e',
	'Jl'=>'Jo&euml;l',
	'Am'=>'Amos',
	'Ab'=>'Abdias',
	'Jon'=>'Jonas',
	'Mi'=>'Mich&eacute;e',
	'Na'=>'Nahum',
	'So'=>'Sophonie',
	'Ag'=>'Agg&eacute;e',
	'Za'=>'Zacharie',
	'Ml'=>'Malachie',
	'Dn'=>'Daniel',
	'Jb'=>'Job',
	'Pr'=>'Proverbes',
	'Qo'=>'Qoh&eacute;leth (Eccl&eacute;siaste)',
	'Ct'=>'Cantiques des cantiques',
	'Rt'=>'Ruth',
	'Lm'=>'Lamentations',
	'Est'=>'Esther',
	'Tb'=>'Tobie',
	'Jdt'=>'Judith',
	'Ba'=>'Baruch',
	'Sg'=>'Sagesse',
	'Si'=>'Siracide (Eccl&eacute;siastique)',
	'Ps'=>'Psaumes',
	'Mt'=>'Matthieu',
	'Lc'=>'Luc',
	'Jn'=>'Jean',
	'Mc'=>'Marc',
	'Ac'=>'Acte des Ap&ocirc;tres',
	'Ro'=>'Romains',
	'1Co'=>'1 Corinthiens',
	'2Co'=>'2 Corinthiens',
	'Ga'=>'Galates',
	'Ep'=>'Eph&eacute;siens',
	'Ph'=>'Philippiens',
	'Col'=>'Colossiens',
	'1Th'=>'1 Thessaloniciens',
	'2Th'=>'2 Thessaloniciens',
	'1Tm'=>'1 Timoth&eacute;e',
	'2Tm'=>'2 Timoth&eacute;e',
	'Tt'=>'Tite',
	'Phm'=>'Phil&eacute;mon',
	'He'=>'H&eacute;breux',
	'Jc'=>'Jacques',
	'1P'=>'1 Pierre',
	'2P'=>'2 Pierre',
	'1Jn'=>'1 Jean',
	'2Jn'=>'2 Jean',
	'3Jn'=>'3 Jean',
	'Jude' => 'Jude',
	'Ap'=>'Apocalypse'
	 ),
	'en' =>array(
		'Gn'=>'Genesis',
		'1Chr'=>'1 Chronicles',
		'1Cor'=>'1 Corinthians',
		'1Jn'=>'1 John',
		'1Mc'=>'1 Maccabees',
		'1Pt'=>'1 Peter',
		'1Kgs'=>'1 Kings',
		'1Sm'=>'1 Samuel',
		'1Thes' =>'2 Thessalonians',
		'2Tm' =>'2 Timothy',
		'1Chr'=>'2 Chronicles',
		'2Cor'=>'2 Corinthians',
		'2Jn'=>'2 John',
		'2Mac' =>'2 Maccabbes',
		'2Pt'=> '2 Peter',
		'2Kgs' =>'2 Kings',
		'2Sm' =>'2 Samuel',
		'2Thes'=>'2 Thessalonians',
		'2Tm' =>'2 Timothy',
		'3Jn'  =>'3 John',
		'Hb' =>'Habakkuk',
		'Ob' =>'Obadiah',
		'Hg'=>'Haggai',
		'Am'=>'Amos',
		'Ap'=>'Apocalypse (Revelation)',
		'Act'=>'Acts of the Apostles',
		'Bar'=>'Baruch',
		'Sg'=>'Song of Songs',
		'Col'=>'Colossians',
		'Dn'=>'Daniel',
		'Dt'=>'Deuteronom',
		'Heb'=>'Hebrews',
		'Eccl'=>'Ecclesiastes',
		'Eph'=>'Ephesians',
		'Esd'=>'Esdras',
		'Est'=>'Esther',
		'Ex'=>'Exodus',
		'Ez'=>'Ezekiel',
		'Phlm'=>'Philemon',
		'Phil'=>'Philippians',
		'Ga'=>'Galates',
		'Jer'=>'Jeremiah',
		'Jas'=>'James',
		'Jb'=>'Job',
		'Jl'=>'Joel',
		'Jon'=>'Jonas',
		'Jn'=>'John',
		'Jude'=>'Jude',
		'Jdt'=>'Judith',
		'Is'=>'Isaiah',
		'Jgs'=>'Judges',
		'Jo'=>'Joshua',
		'Lam'=>'Lamentations',
		'Lk'=>'Luk',
		'Lv'=>'Levitic',
		'Mal'=>'Malachi',
		'Mk'=>'Mark',
		'Mt'=>'Matthieu',
		'Mi'=>'Micah',
		'Na'=>'Nahum',
		'Neh'=>'Nehemiah',
		'Nm'=>'Numbers',
		'Hos'=>'Hosea',
		'Prv'=>'Proverbs',
		'Rom'=>'Romans',
		'Ru'=>'Ruth',
		'Ps'=>'Psalms',
		'Ws'=>'Wisdom',
		'Sir'=>'Sirach',
		'Zep'=>'Zephaniah',
		'Ti'=>'Titus',
		'Tb'=>'Tobit',
		'Zec'=>'Zechariah'
	)	 
	 
);






$tableau_separateur = array(
	'fr'=>',',
	'en'=>':');

$tableau_traduction = array(
	'jerusalem' => array(
		'traduction'=> 'Bible de J&eacute;rusalem',
		'gateway'	=> false,
		'lang'		=> 'fr'),
	'kj'		=> array(
		'traduction'=>'King Jame',
		'gateway'	=>9,
		'lang'		=>'en'
	)
);



?>